### ISSUE TITLE
How to define multivariable function

### ISSUE THREAD

**Issue by felixcra** [autodiff/autodiff#102]
I'd like to implement the following function:

![CodeCogsEqn (2)](https://user-images.githubusercontent.com/28649168/74000228-536d7c80-4935-11ea-8fb2-54a15cdd98d7.gif)

where `n`, `y(1),...,y(n)` and `t(1),...,t(n)` are constant scalars and α and ω are the two scalar function arguments. How would you recommend to implement this for forward mode? I tried a number of things, but I ran into `std::bad_alloc` issues and other weird behaviour.

**Comment by supersega** [comment]
Hi, felixcra. Could you please send a minimal example. And then we can investigate bad alloc.

**Comment by allanleal** [comment]
Please reopen if further info is given.
