### ISSUE TITLE
How to use autodiff without using namespaces?

### ISSUE THREAD

**Issue by mallrez** [autodiff/autodiff#103]
In the given examples I see everywhere the definition of 
using namespace autodiff
using namespace Eigen.

I tried to compile the examples without using namespaces however it was not clear to me where the typedef VectorXdual belongs to.
I always get the error
 _error: ‘Vector2dual’ is not a member of ‘autodiff’_
or that it does not belong to eigen.

Could you help me out with this? So what would be VectorXdual without namespaces?
Thanks in advance

**Comment by allanleal** [comment]
Hi @mallrez . The `Vector2dual` type is in the `autodiff` namespace. Can you post a minimal example reproducing your issue?

**Comment by mallrez** [comment]
Hej,
Thank you very much for you quick answer!
So I try to use the example-forward-jacobian-derivatives-using-eigen.cpp example and I want to get rid of using namespaces.
That's what I came up with:

`
    // C++ includes
   #include <iostream>
   using namespace std;

   // Eigen includes
   #include <Eigen/Core>
   // using namespace Eigen;

   // autodiff include
   #include <autodiff/forward.hpp>
   #include <autodiff/forward/eigen.hpp>
   // using namespace autodiff;

   // The vector function for which the Jacobian is needed
   autodiff::VectorXdual f(const autodiff::VectorXdual& x)
   {
       return x * x.sum();
   }

   int main()
   {
       autodiff::VectorXdual x = Eigen::MatrixXd::Random(10,1);    // the input vector x with 5 variables

       autodiff::VectorXdual F;  // the output vector F = f(x) evaluated together with Jacobian matrix    below

    Eigen::MatrixXd J = autodiff::forward::jacobian(f, autodiff::forward::wrt(x), autodiff::forward::at(x), F);  // evaluate the output vector F and the Jacobian matrix dF/dx

    cout << "F = \n" << F << endl;  // print the evaluated output vector F
    cout << "J = \n" << J << endl;  // print the evaluated Jacobian matrix dF/dx
} 
`
However when compiling I get these errors:
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp: At global scope:
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:15:11: error: ‘VectorXdual’ in namespace ‘autodiff’ does not name a type
 autodiff::VectorXdual f(const autodiff::VectorXdual& x)
           ^~~~~~~~~~~
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:23:15: error: ‘VectorXdual’ is not a member of ‘autodiff’
     autodiff::VectorXdual x = Eigen::MatrixXd::Random(10,1);    // the input vector x with 5 variables
               ^~~~~~~~~~~
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:26:15: error: ‘VectorXdual’ is not a member of ‘autodiff’
     autodiff::VectorXdual F;  // the output vector F = f(x) evaluated together with Jacobian matrix below
               ^~~~~~~~~~~
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:28:53: error: ‘f’ was not declared in this scope
     Eigen::MatrixXd J = autodiff::forward::jacobian(f, autodiff::forward::wrt(x), autodiff::forward::at(x), F);  // evaluate the output vector F and the Jacobian matrix dF/dx
                                                     ^
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:28:79: error: ‘x’ was not declared in this scope
     Eigen::MatrixXd J = autodiff::forward::jacobian(f, autodiff::forward::wrt(x), autodiff::forward::at(x), F);  // evaluate the output vector F and the Jacobian matrix dF/dx
                                                                               ^
~/autodiff/examples/forward/example-forward-jacobian-derivatives-using-eigen.cpp:28:109: error: ‘F’ was not declared in this scope
     Eigen::MatrixXd J = autodiff::forward::jacobian(f, autodiff::forward::wrt(x), autodiff::forward::at(x), F);  // evaluate the output vector F and the Jacobian matrix dF/dx
                                                                                                             ^

**Comment by allanleal** [comment]
Hi, I'm going to push a fix for this in a moment.

~~~cpp
// C++ includes
#include <iostream>
using namespace std;

// Eigen includes
#include <Eigen/Core>
// using namespace Eigen;

// autodiff include
#include <autodiff/forward.hpp>
#include <autodiff/forward/eigen.hpp>
// using namespace autodiff;

// The vector function for which the Jacobian is needed
autodiff::VectorXdual f(const autodiff::VectorXdual &x) { return x * x.sum(); }

int main()
{
  autodiff::VectorXdual x = Eigen::MatrixXd::Random(10, 1); // the input vector x with 5 variables

  autodiff::VectorXdual F; // the output vector F = f(x) evaluated together with
                           // Jacobian matrix    below

  Eigen::MatrixXd J = autodiff::forward::jacobian(f, autodiff::forward::wrt(x), autodiff::forward::at(x), F); // evaluate the output vector F and the Jacobian matrix dF/dx

  cout << "F = \n" << F << endl; // print the evaluated output vector F
  cout << "J = \n" << J << endl; // print the evaluated Jacobian matrix dF/dx
}
~~~
