### ISSUE TITLE
Considering using autodiff, have some questions

### ISSUE THREAD

**Issue by DanPuzzuoli** [autodiff/autodiff#113]
Hi,

I'm about to start a project that requires automatic differentiation; I have a small set of specific requirements (e.g. I don't need any high level Machine learning functionality) and am trying to find a package for automatic differentiation that balances being lightweight with support for these requirements (or at least, is not too hard to implement these). I like the looks of `autodiff`, though I have a few questions: 

1. Does `autodiff` have any support for complex numbers? Note: I only want to take derivatives with respect to real parameters (i.e. no complex differentiation), but want to differentiate functions f : R^n -> R^k with intermediate computations using complex numbers, or functions f : R^n -> C^k.  
2. The computations I would like to differentiate include solving differential equations. Is there any chance of using existing DE solvers in conjunction with `autodiff`, or do you think it would be necessary to write a solver from scratch to incorporate `autodiff`?
3. Some DE solving methods I would like to use involve matrix exponentials. Similar to question 2: do you think doing this using `autodiff` would require rewriting a matrix exp function from scratch?

Thanks in advance.

**Comment by allanleal** [comment]
Hi @DanPuzzuoli ,

1. Both the number types in `autodiff` are template classes, so you can use `std::complex<double>` with them. I think there is an example provided by @supersega . Based on your function type, you most likely want to use forward-mode differentiation.

2. If you want want to provide the Jacobian to the existing solver, this is possible. If you want the existing ODE/PDE solver to propagate the chain of derivative evaluations, then this will depend on how flexible the solver is with respect to using custom types. 

3. See (2) above.

**Comment by DanPuzzuoli** [comment]
Okay thank you!
