### ISSUE TITLE
Compiling errors

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#12]
I got a ton of errors when trying to compile the [Jacobian example](https://autodiff.github.io/tutorials/#jacobian-of-a-vector-function)

> Karls-Mac-mini:scrap karl$ g++ jacobian.cpp -o jacobian.o && ./jacobian.o
> In file included from jacobian.cpp:10:
> In file included from /usr/local/include/autodiff/forward.hpp:33:
> /usr/local/include/autodiff/forward/forward.hpp:213:17: error: unknown type name 'constexpr'
> struct isExpr { constexpr static bool value = false; };
>                 ^
> /usr/local/include/autodiff/forward/forward.hpp:213:27: error: expected member name or ';' after
>       declaration specifiers
> struct isExpr { constexpr static bool value = false; };

(This is just the first few lines)

Am I using the wrong compiler?

**Comment by kewp** [comment]
Nevermind - I needed to enforce the C++17 standard

> g++ -std=c++17 jacobian.cpp -o jacobian.o && ./jacobian.o

(BTW I'm running this on a Mac)

Works great now.

> Karls-Mac-mini:scrap karl$ g++ -std=c++17 jacobian.cpp -o jacobian.o && ./jacobian.o
> u = 
> 15
> 30
> 45
> 60
> 75
> du/dx = 
> 16  1  1  1  1
>  2 17  2  2  2
>  3  3 18  3  3
>  4  4  4 19  4
>  5  5  5  5 20

**Comment by allanleal** [comment]
Great you figured out!

If you use cmake, check this [tutorial](https://autodiff.github.io/tutorials/#integration-with-cmake-based-projects) on how to use `find_package(autodiff)` and then `target_link_library(myapp autodiff::autodiff)`.

The command `target_link_library(myapp autodiff::autodiff)` will ensure that C++17 is enabled automatically.

**Comment by kewp** [comment]
Oh great, that's useful. I've been meaning to try cmake. Thanks for the tip!
