### ISSUE TITLE
Errors in Visual Studio

### ISSUE THREAD

**Issue by printablealice** [autodiff/autodiff#121]
Hi,

Thank you very much for this code, I am really excited to start working with it.
I can successfully run the examples in Visual Studio 2017, but I get errors (which as far as I can tell do not affect how the code runs).
My guess is that this is just Visual Studio getting "confused," but I wanted to be sure.

I apologize if this is a really basic/obvious issue, I'm quite inexperienced in software development.

E.g. for **example-forward-jacobian-derivatives-using-eigen** I see

```
Error (active)	E0312
no suitable user-defined conversion from "autodiff::forward::MulExpr<autodiff::forward::PreventExprRef<const autodiff::VectorXdual &>, autodiff::forward::PreventExprRef<autodiff::forward::dual>>" to "autodiff::VectorXdual" exists
example-forward-jacobian-derivatives-using-eigen
...\examples\forward\example-forward-jacobian-derivatives-using-eigen.cpp
17	

Error (active)	E0349
no operator "<<" matches these operands
example-forward-jacobian-derivatives-using-eigen
...\examples\forward\example-forward-jacobian-derivatives-using-eigen.cpp
23
operand types are: autodiff::VectorXdual << int
```

![image](https://user-images.githubusercontent.com/5091875/85766987-6ad2b980-b6cc-11ea-993b-281c1dd7ce58.png)

but the code runs just fine and produces

```
F =
15
30
45
60
75
J =
16  1  1  1  1
 2 17  2  2  2
 3  3 18  3  3
 4  4  4 19  4
 5  5  5  5 20
```

**Comment by allanleal** [comment]
Hi James. This seems like an false positive of MSVC Intellisense. There is actually no build errors - that's why you are able to compile and run. Unfortunately, I'm not a MSVC user and it's not clear to me what could be done to avoid this Intellisense issue. I'll ping some colleagues here that I think use MSVC to see if there is a way to eliminate this:

@supersega , @tadeu , @danilomendesdia

**Comment by supersega** [comment]
Hi all, Intellisense may produce such false positive errors. No worries. Just use output from compiler to detect if code has errors/warnings.

**Comment by printablealice** [comment]
Gotcha!--Thank you very much :)
