### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by benjaminhuth** [autodiff/autodiff#127]
Hi, 
I have a question regarding versioning. There exists a label with version 0.5.10, but actually this seems to be also marked as 0.5.9 in the `CMakeLists.txt`. 
Regardless this, would it be possible to release a new version, so that I can check if the version contains the latest changes (`std::hypot`, etc...).

**Comment by volpatto** [comment]
Hi, @benjaminhuth 

I think you are right. The correct source of versioning is the version control system, I mean, the release tag which we can verify through the GitHub. I think that `CMakeLists.txt` is not up to date.

Maybe we just should bump the version in the CMakeLists...

**Comment by volpatto** [comment]
BTW, the latest release is from 02/2020. So `autodiff` doesn't have a release with the changes you mentioned. Maybe @allanleal can help you with a new release.

**Comment by benjaminhuth** [comment]
Yeah, sure the commit hash is for sure better suited for this. It is just (at least to my knowledge) not usable when using CMake's `find_package(...)` method.

**Comment by allanleal** [comment]
Hi @benjaminhuth , I have just created release [v0.5.11](https://github.com/autodiff/autodiff/releases/tag/v0.5.11). Also bumped the library version in the `CMakeLists.txt` file (in case you are using `find_package(autodiff 0.5.11)`.
