### ISSUE TITLE
Conversion to Double

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#13]
I have a function which returns a `var`. How do I then do a calculation such as `fabs(a-0.001)`? I'm getting the error

```
error: cannot convert ‘autodiff::var’ to ‘double’ in assignment
```

**Comment by kewp** [comment]
I got it - `val(a)` :)

**Comment by allanleal** [comment]
Hmmm maybe ir makes sense to overload `fabs` (and also `abs`) in autodiff, so that you don't need to use `val` at all.
