### ISSUE TITLE
Complex conjugate not working

### ISSUE THREAD

**Issue by tnguyen-ornl** [autodiff/autodiff#134]
I'm following the example https://github.com/autodiff/autodiff/blob/master/examples/forward/example-forward-single-variable-function-custom-scalar.cpp

When trying to use `conj` on the `cxdual` type, it didn't do any conjugation.

Reproduce code:
```
#include <iostream>
#include <complex>
using namespace std;

// autodiff include
#include <autodiff/forward.hpp>
using namespace autodiff;

// Specialize isNumber for complex to make it compatible with dual
namespace autodiff::forward::traits {
template<typename T>
struct isArithmetic<complex<T>> : std::true_type { };
} // autodiff::forward::traits

using cxdual = forward::Dual<complex<double>, complex<double>>;

// The single-variable function for which derivatives are needed
cxdual f(cxdual x)
{
    return conj(x);
}

int main()
{
    constexpr std::complex<double> I { 0.0, 1.0 };
    cxdual x = 2.0 + 1.0 * I;   // the input variable x
    cxdual u = f(x);  // the output variable u
    cout << "u = " << u << endl;         // print the evaluated output u
}
```

`f` returns the original value, which is wrong (should return the complex conjugate).

I'm not sure the implication w.r.t. derivative calculation yet.

Could you please advise how to fix this issue while making sure the derivative can be computed?

**Comment by allanleal** [comment]
Could you please try instead:

~~~cpp
using cxdual = std::complex<dual>;
~~~

which will be a proper `std::complex` type supported by STL?

I think the example above was contributed by @supersega . I don't use `autodiff` + `std::complex` in my research, so maybe @supersega could advise you (but I would try the above definition of `cxdual` first).

**Comment by tnguyen-ornl** [comment]
That works. Thanks, @allanleal.
