### ISSUE TITLE
Show Propogation

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#14]
Is there any way to see what is inside a `var` or perhaps it's derivative? I keep getting zero for my `dud(x)` and I want to see what's inside. Any suggestions?

**Comment by allanleal** [comment]
The method `val` should give you the current value of the `var` number (e.g., `val(a)`).

This is defined as:

~~~c++
/// Return the value of a variable x.
inline double val(const var& x)
{
    return x.expr->val;
}
~~~

So, maybe you want to check the member pointer `expr` and its attribute `val` .

~~~c++
struct Expr
{
    /// The numerical value of this expression.
    double val;

    /// Construct an Expr object with given numerical value.
    explicit Expr(double val) : val(val) {}

...
~~~

As to the current derivative, this wont work, because they are not stored inside the `var` numbers.

**Comment by allanleal** [comment]
Can you post a minimum example that shows the anomaly?

**Comment by kewp** [comment]
I did manage to get this working. Though for future reference it would be nice to see the expression tree...

**Comment by allanleal** [comment]
> I did manage to get this working

Great.

> Though for future reference it would be nice to see the expression tree...

What do you mean by `see the expression tree`?

**Comment by kewp** [comment]
Not sure how to explain it. So `var` is actually an entire list of numeric operations? And you differentiate by using the chain rule, _after_ storing out every operation that has been done to it? Am I correct this far?

So the `expression tree` is just a list of what is inside of the `var` - the `plus` and `minus` and etc. that will eventually become the `double` when you evaluate.... Or am I completely off base?

**Comment by allanleal** [comment]
> Not sure how to explain it. So var is actually an entire list of numeric operations? And you differentiate by using the chain rule, after storing out every operation that has been done to it? Am I correct this far?

More or less this. Each `var` has the entire operation history, which is organized as an expression tree, built as arithmetic operators, math functions, etc, are used on them.

Only when the user ask to compute the derivatives is that this tree is traversed to compute them (when you call the method `derivatives`:

~~~c++
var x = 1.0;
var y = 2.0;
var z = 3.0;
var u = f(x, y, z);

Derivatives dud = derivatives(u);

double dudx = dud(x);
double dudy = dud(y);
double dudz = dud(z);
~~~

> So the expression tree is just a list

It's a binary tree. Some operations will create two branches (e.g., `+`, `*`), other just one branch (e.g., `sin`, exp`, etc.).

I'm aware there is a lack of documentation there on how these derivatives are computed, and stored, etc. For now, you might want to inspect the header file `autodiff/reverse/reverse.hpp`. But I know, this is not as helpful as a proper documentation! ;)

**Comment by kewp** [comment]
That's OK. The header file is easy enough to understand. I'm closing this issue.

**Comment by allanleal** [comment]
Last thing: have you tried the `forward mode` - it could be more efficient than reverse. I'm this only a benchmark can tell.

**Reason:** The reverse mode has the overhead of constructing this expression tree at *runtime*. The forward mode creates as much as possible "chunks of expression trees" at complile time, using template metaprogramming (to avoid temporaries, and also allow some optimizations of the expression, for example, `-(-x)` becomes `x` at compile time).

**Comment by kewp** [comment]
Thanks, I will try that. I just want to get the code working! And the reverse mode header file is a lot easier for me to understand.
