### ISSUE TITLE
Error including autodiff header files in mex-application

### ISSUE THREAD

**Issue by matthiaskaldorf** [autodiff/autodiff#142]
Dear all,
first of all, thanks for providing this toolbox and its link to Eigen. Then, my apologies for trying to use this through MATLAB, but this is unfortunately standard in my field. I am for the moment simply trying to include an autodiff-header into my cpp-file, which I then call from within MATLAB, i.e. I am just using

using namespace std;
#include <autodiff/reverse.hpp>

The entire file is then compiled using:

mex -I'C:\Matthias\M-methods\Eigen\eigen-3.3.9\' -I'C:\Matthias\M-methods\autodiff\autodiff\' myfile.cpp

This leads to a large bunch of errors which I have trouble disentangling and are pasted below. The filepath is specified correctly, so I suspect I have to specify some compiler options? Any help would be greatly appreciated.

Best, Matthias

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:50:25: error: 'invoke_result_t' in namespace 'std' does not name a
template type
 using ReturnType = std::invoke_result_t<Fun, Args...>;
                         ^~~~~~~~~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:53:16: warning: variable templates only available with -std=c++14
or -std=gnu++14
 constexpr bool isNumber = std::is_arithmetic<PlainType<T>>::value;
                ^~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:56:16: warning: variable templates only available with -std=c++14
or -std=gnu++14
 constexpr bool isArithmetic = std::is_arithmetic<PlainType<T>>::value;
                ^~~~~~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:59:28: error: 'tuple_size_v' is not a member of 'std'
 constexpr auto TupleSize = std::tuple_size_v<std::decay_t<Tuple>>;
                            ^~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:59:46: error: 'decay_t' is not a member of 'std'
 constexpr auto TupleSize = std::tuple_size_v<std::decay_t<Tuple>>;
                                              ^~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:59:64: error: expected primary-expression before '>>' token
 constexpr auto TupleSize = std::tuple_size_v<std::decay_t<Tuple>>;
                                                                ^~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:59:66: error: expected primary-expression before ';' token
 constexpr auto TupleSize = std::tuple_size_v<std::decay_t<Tuple>>;
                                                                  ^
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:59:16: warning: variable templates only available with -std=c++14
or -std=gnu++14
 constexpr auto TupleSize = std::tuple_size_v<std::decay_t<Tuple>>;
                ^~~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:62:39: error: 'TupleHead' function uses 'auto' type specifier
without trailing return type
 constexpr auto TupleHead(Tuple&& tuple)
                                       ^
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:62:39: note: deduced return type only available with -std=c++14 or
-std=gnu++14
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:68:39: error: 'TupleTail' function uses 'auto' type specifier
without trailing return type
 constexpr auto TupleTail(Tuple&& tuple)
                                       ^
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:68:39: note: deduced return type only available with -std=c++14 or
-std=gnu++14
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp: In function 'constexpr auto autodiff::detail::TupleTail(Tuple&&)':
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:70:18: error: use of 'auto' in lambda parameter declaration only
available with -std=c++14 or -std=gnu++14
     auto g = [&](auto&&, auto&&... args) constexpr {
                  ^~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:70:26: error: use of 'auto' in lambda parameter declaration only
available with -std=c++14 or -std=gnu++14
     auto g = [&](auto&&, auto&&... args) constexpr {
                          ^~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:70:36: error: expansion pattern 'int&&' contains no argument packs
     auto g = [&](auto&&, auto&&... args) constexpr {
                                    ^~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp: In lambda function:
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:70:42: error: expected '{' before 'constexpr'
     auto g = [&](auto&&, auto&&... args) constexpr {
                                          ^~~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp: In function 'constexpr auto autodiff::detail::TupleTail(Tuple&&)':
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:70:42: error: expected ',' or ';' before 'constexpr'
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:73:12: error: 'apply' is not a member of 'std'
     return std::apply(g, std::forward<Tuple>(tuple));
            ^~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp: At global scope:
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:81:15: error: 'constexpr autodiff::detail::Index<i>::operator
size_t() const' cannot be overloaded
     constexpr operator size_t() { return index; }
               ^~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:80:15: error: with 'constexpr autodiff::detail::Index<i>::operator
size_t() const'
     constexpr operator size_t() const { return index; }
               ^~~~~~~~
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:85:35: error: 'AuxFor' function uses 'auto' type specifier without
trailing return type
 constexpr auto AuxFor(Function&& f)
                                   ^
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:85:35: note: deduced return type only available with -std=c++14 or
-std=gnu++14
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp: In function 'constexpr auto autodiff::detail::AuxFor(Function&&)':
C:\Matthias\M-methods\autodiff\autodiff/autodiff/common/meta.hpp:87:8: error: expected '(' before 'constexpr'
     if constexpr (i < iend) {
        ^~~~~~~~~
C:\Matthias\Projekte\202011 QE FX\Code Matthias\ini_residuals.cpp:192:1: error: expected '}' at end of input
 }
 ^
C:\Matthias\Projekte\202011 QE FX\Code Matthias\ini_residuals.cpp: At global scope:
C:\Matthias\Projekte\202011 QE FX\Code Matthias\ini_residuals.cpp:192:1: error: expected '}' at end of input
C:\Matthias\Projekte\202011 QE FX\Code Matthias\ini_residuals.cpp:192:1: error: expected '}' at end of input

**Comment by allanleal** [comment]
You need somehow to instruct `mex` to use `-std=c++17` for the compilation. I don't know how to do this.
