### ISSUE TITLE
Sparsity pattern of Hessian

### ISSUE THREAD

**Issue by sergeigribanov** [autodiff/autodiff#159]
Is it possible to implement a computation of the sparsity pattern of hessian? (see work https://gowerrobert.github.io/pdf/reports/Hessian_sparsity.pdf) In many cases it can be a very useful feature. For example, when solving optimization problems, in some cases, you have to invert a hessian. Knowing the sparsity pattern, one can use inversion algorithms for sparse matrices (for example, see https://eigen.tuxfamily.org/dox/group__TopicSparseSystems.html).

**Comment by allanleal** [comment]
If you know beforehand the sparsity pattern, then it should be possible to skip the derivative evaluations that are zero. This is not implemented. One could nevertheless implement his own code for Hessian calculation using autodiff's higher-order `dual` number.

**Comment by sergeigribanov** [comment]
Thank you! By the way, do you have any articles or manuals except this one https://autodiff.github.io? I am new to automatic differentiation, however, as it seems to me, this can greatly simplify and speed up the optimization problem that I am solving.
