### ISSUE TITLE
Derivatives w.r.t. `var` and references

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#16]
Can you tell me if the following code makes sense?

```
var w = energy(m, D);
VectorXvar u(2*m.nn);
        
int i; for (i=0; i<m.nn; i++)
{
    u(2*i) = m.one[i];
    u(2*i+1) = m.two[i];
}
        
VectorXd dwdu = gradient(w,u);
```

So I'm building up a `VectorXvar` from two lists I have (my degrees of freedom) and then differentiation the energy with this new list. Will this work? I'm getting all zeros and I wonder if it's because I'm not using the variables directly but rather building a new list....

**Comment by allanleal** [comment]
I don't see `w` being computed using the `var` variables in the vector `u` - so that's why the zero derivatives of `w` with respect to `u` components.

**Comment by allanleal** [comment]
I'll close this since I guess it was clarified in other discussions we had recently in other issues. If I'm mistaken, please reopen!

**Comment by kewp** [comment]
w is computed using two sets of VectorXvar - m.one and m.two (m is a struct). So I’m copying over those values into one single large VectorXvar so I can get the vector of derivatives of all of them.

I guess my question really was about copying vars - will they be tracked or has the equals overload somehow lost the fact that (in the code above) u[0] for example is the same as m.one[0].

That’s part of a bigger issue / confusion I’ve been having with your library. How vars (and duals) are tracked. I’m on my phone but I’ll put up a code example to explain once I’m at a desktop

**Comment by allanleal** [comment]
The `var` type is a wrapper to a `std::shared_ptr<Expr>`. Copying `var`s around is safe and preserve the dependency semantics. For example:

~~~
var x = 2.0;
var t = x;  // t is identical to x (the undelying shared_ptr is the same)
~~~

My recommendation is that you implement all your functions as you would using `double`. You should not worry about such details. If then any error pops up, then we are more likely certain that is a bug in the `autodiff` library and not in an inconsistent usage of `autodiff` types.

**Comment by kewp** [comment]
This sounds like a great tip but I’m having a hard time understanding it - can you give me an example of not “implementing everything as I would with double”? Do you mean things like passing in structs? The function I need a derivative of is very complex and involves various levels of inner operation. I can’t just set it up as with doubles

**Comment by allanleal** [comment]
> This sounds like a great tip but I’m having a hard time understanding it

Let's assume you have:

~~~c++
dual f(dual x, dual y)
{
    double x2 = x * x; // dual expression converted to double
    double y2 = y * y; // dual expression converted to double

    return sqrt(x2 + y2); // return is a constant dual, and any derivative wrt x or y are zero
}
~~~

**Comment by kewp** [comment]
Right, this is what I have struggled with - tracking variable usage. So as you show, any time you assign to a double you loose history. And if you do that once by mistake (and then try use that double in another var expression) you will get errors without knowing why.

That is why I would still like to recommend something like a special print function which shows the expression tree of a var, perhaps to a certain depth and with variables names if possible? I could take a crack at it if you maybe give me a few pointers of how one might go about it

**Comment by allanleal** [comment]
>  And if you do that once by mistake (and then try use that double in another var expression) you will get errors without knowing why.

Exactly - the code will run just fine, but the derivatives are not correct. Looking at the example I just wrote above, the rule of thumb is to use `auto` everywhere (even when you have constants):

~~~c++
dual f(dual x, dual y)
{
    const auto R = 8.314;
    const auto x2 = x * x;
    const auto y2 = y * y;

    return R * sqrt(x2 + y2);
}
~~~

**Comment by kewp** [comment]
Hmmm ok, I’ll try give the source
a look and see if I can start with this. It would help me too to debug. I might need some help with modern c++ techniques since I have only really worked with the old one.

I like the idea of serialization. It will be hard to visualize with just console output, so I’m thinking of graphing the dependencies somehow. Much like the graphics on your autodiff webpage

**Comment by allanleal** [comment]
If we can put the entire contents of a `var` expression tree in a JSON or YAML file, we can later use this as input in a converting script that will output in other more visual forms (HTML figures, TikZ diagrams for latex publications, etc.).

**Comment by kewp** [comment]
Ruining a bit behind with work but I will get to this
