### ISSUE TITLE
How does Eigen and xtensor compatibility?

### ISSUE THREAD

**Issue by Roy-Kid** [autodiff/autodiff#183]
Hi, we want to use autodiff to develop a molecular forcefield in computational chemistry. Our code involves a large number of matrix operations so we want to combine Eigen or xtensor with autodiff. So do you test the compatibility of those linalg lib with this brilliant work?

**Comment by allanleal** [comment]
Hi, `autodiff` supports Eigen at the moment (see [tutorials](https://autodiff.github.io/tutorials/)), but there is no plan at the moment to also support xtensor.
