### ISSUE TITLE
Missing atan2 for type real

### ISSUE THREAD

**Issue by artivis** [autodiff/autodiff#185]
The function `atan2` is not overloaded for the `autodiff::real` type.

**Comment by allanleal** [comment]
Hi @artivis - would you kindly work on this? Here are my notes on the higher-order derivative expressions for `real`:

[higher-order-derivatives-formulas.pdf](https://github.com/autodiff/autodiff/files/7200296/higher-order-derivatives-formulas.pdf)

Unfortunately, these are only notes. I haven't published them and they are not explained in-depth. You should though be able to infer from there how to derive the expression for `tan2` and maybe the missing others.

**Comment by bostoncleek** [comment]
I am working on a PR to add `atan2`. The picture below contains the derivations for when `atan2` is used with a scalar and a dual number. I have been using PR https://github.com/autodiff/autodiff/pull/116 as a reference.

I am struggling to derive the equations for `atan2(y,x)` when both `x` and `y` are dual numbers. @allanleal 

![atan2](https://user-images.githubusercontent.com/36201047/165611004-aed195a7-9151-45d3-a2cb-3d99aff78986.png)

**Comment by bostoncleek** [comment]
closed y https://github.com/autodiff/autodiff/pull/226
