### ISSUE TITLE
Expression template-based reverse(?) autodiff

### ISSUE THREAD

**Issue by jdh8** [autodiff/autodiff#195]
I'm interested in implementing autodiff based on expression templates. This would enable compile-time symbolic differentiation that reduces runtime cost. However, this may restrict runtime functionality such as dynamically creating expressions. How do you think about this idea? Where should I put the header? (`autodiff/reverse/expr.hpp`?)

**Comment by allanleal** [comment]
I'm not sure about what you want to do. Could you please elaborate?
autodiff already uses expression templates for compile-time generation of
the derivative expressions when using the dual type (forward mode
derivative computation). Do you mean doing this for reverse mode? I'm not
sure this would be practical (e.g., when runtime branching (if/else) would
be needed).

**Comment by jdh8** [comment]
We can store the types of subexpressions as template arguments. This implementation features static dispatch onto subexpressions.

```cpp
#include <utility>

template <typename T, typename Derived>
struct Expr
{
    const Derived& cast() const { return *static_cast<const Derived*>(this); }

    template <typename... Args>
    auto eval(Args&&... args)
    {
        return cast().eval(std::forward<Args>(args)...);
    }
};

template <typename T>
struct Constant : Expr<T, Constant<T>>
{
    T value;

    constexpr Constant(T v) : value(v) {}

    template <typename... Args>
    T eval(Args&&... args) { return value; }
};

template <typename T>
struct Variable : Expr<T, Variable<T>>
{
    std::size_t index;

    explicit constexpr Variable(std::size_t i) : index(i) {}

    //TODO Find a better evaluation API
    T eval(const T* vec, std::size_t n) { return vec[index]; }
};

//TODO Allow sum of multiple expressions
template <typename T, typename X, typename Y>
struct SumExpr : Expr<T, SumExpr<T, X, Y>>
{
    X x;
    Y y;

    constexpr SumExpr(X x, Y y) : x(x), y(y) {}

    template <typename... Args>
    auto eval(Args&&... args)
    {
        return x.eval(std::forward<Args>(args)...) + y.eval(std::forward<Args>(args)...);
    }
};

//TODO Allow sum of multiple expressions
template <typename T, typename X, typename Y>
struct ProdExpr : Expr<T, ProdExpr<T, X, Y>>
{
    X x;
    Y y;

    constexpr ProdExpr(X x, Y y) : x(x), y(y) {}

    template <typename... Args>
    auto eval(Args&&... args)
    {
        return x.eval(std::forward<Args>(args)...) * y.eval(std::forward<Args>(args)...);
    }
};

template <typename T, typename X, typename Y>
SumExpr<T, X, Y> operator+(const Expr<T, X>& x, const Expr<T, Y>& y)
{
    return { x.cast(), y.cast() };
}

template <typename T, typename X, typename Y>
ProdExpr<T, X, Y> operator*(const Expr<T, X>& x, const Expr<T, Y>& y)
{
    return { x.cast(), y.cast() };
}

template <typename T>
Constant<T> diff(const Constant<T>&, const Variable<T>&)
{
    return 0;
}

template <typename T>
Constant<T> diff(const Variable<T>& expr, const Variable<T>& var)
{
    return expr.index == var.index;
}

template <typename T, typename X, typename Y>
auto diff(const SumExpr<T, X, Y>& sum, const Variable<T>& var)
{
    return diff(sum.x, var) + diff(sum.y, var);
}

template <typename T, typename X, typename Y>
auto diff(const ProdExpr<T, X, Y>& prod, const Variable<T>& var)
{
    return diff(prod.x, var) * prod.y + prod.x * diff(prod.y, var);
}
```

**Comment by allanleal** [comment]
I see. What are your thoughts in case there are branches? Also, what is the
usage (say, an example in a main function) going to look like? Variable
needs to have a unique index; what is your idea on automating this process?
BTW, I'm on vacation, so not as responsive as usual.

**Comment by jdh8** [comment]
I don't think it's a good idea to have indexed variables. I was just trying to give a minimal example. I didn't even incorporate `wrt` system here.

Only if the types are different on branches would cause a problem. We can have a branch operator or a generic/opaque expression type.

The usage should be pretty similar to current API
```cpp
var x, y, z;
auto u = f(x, y, z); // can be a complicated expression type

auto [ux, uy, uz] = derivatives(u, wrt(x, y, z));
```

**Comment by jdh8** [comment]
I think I'm not very sure what I was talking about and whether it's forward, backward, or mixed autodiff. I'm closing this issue until I have a more concrete idea.
