### ISSUE TITLE
Converting ArrayXreal to Eigen::VectorXd

### ISSUE THREAD

**Issue by izsahara** [autodiff/autodiff#196]
As with the title,
Basically im following the example in 

https://github.com/autodiff/autodiff/blob/master/examples/forward/example-forward-gradient-derivatives-using-eigen.cpp

But inside my function i pass the `ArrayXreal` into another function that takes on a `const Eigen::VectorXd&` i.e.

```
namespace ad = autodiff;
ad::real log_marginal_likelihood(const ad::ArrayXreal& theta) override {
	// set_params recieves a const Eigen::VectorXd&
        // Anything here that i could do a conversion?
	gpr.set_params(theta);
	//

	ad::real NLL = 0.5 * (gpr.outputs.transpose() * gpr.alpha)(0)
		+ gpr.chol.matrixLDLT().diagonal().array().log().sum()
		+ (0.5 * gpr.inputs.rows()) * log(2.0 * PI);
	NLL -= log_prior();
	return NLL;
```

Thanks

**Comment by izsahara** [comment]
I solved it by doing this, although for some reason my gradients are 0. I wonder whether im applying AD correctly 
```
ad::real objective_fxn(const ad::ArrayXreal& theta) override {
  TVector tt(theta.size());
  for (int i = 0; i < theta.size(); ++i) {
	  tt[i] = static_cast<double>(theta[i]);
  }				
  gpr.set_params(tt);
  double NLL = 0.5 * (gpr.outputs.transpose() * gpr.alpha)(0) 
					  + gpr.chol.matrixLDLT().diagonal().array().log().sum() 
					  + (0.5 * gpr.inputs.rows()) * log(2.0 * PI);
  NLL -= log_prior();
  ad::real res = NLL;
  return res;
}
```

For what its worth, the context here is minimizing the log marginal likelihood (`NLL`) for a Gaussian Process. Any suggestions regarding this, would be much appreciated. Thanks

**Comment by allanleal** [comment]
Hi @izsahara . As soon as you convert `theta` to a vector of `double` values, you stop propagation of automatic derivatives. You need to carry on all computations with `autodiff::real`. Try to use `double` only for constants (e.g., universal gas constant, speed of light, etc). Let me know if this helps. I'll close the issue, but please reopen in case you still believe there is an issue.
