### ISSUE TITLE
Higher-order derivatives using forward mode?

### ISSUE THREAD

**Issue by versatran01** [autodiff/autodiff#2]
Hi thanks for this work.

I was just wondering is it possible to do higher-order derivatives using forward mode?

**Comment by allanleal** [comment]
Hi @versatran01 .

The type `dual` in `autodiff`, used for forward automatic differentiation, is just a type alias to `Dual<double>`. If you define your `dual` as:

```c++
using dual = Dual<Dual<double>>;
```

you should then be able to compute both 1st and 2nd order derivatives. 

You can make this indefinitely deeper as needed. 

I just saw that a minor change in the code is needed - change `double` return type below:

```c++
template<typename Function, typename T, typename... Args>
double derivative(const Function& f, Dual<T>& wrt, const Args&... args)
```
to template type `T`:

```c++
template<typename Function, typename T, typename... Args>
T derivative(const Function& f, Dual<T>& wrt, const Args&... args)
```

I'll do this and add some examples in the documentation.

**Comment by versatran01** [comment]
Thanks a lot.
One more question if I have a vector function Y = f(x), where Y is [Y1, Y2, Y...] and x is a single variable, and I'd like to compute the derivative of dY/dx which is a vector. In this case, do you recommend using forward or reverse mode? Would forward mode be faster in this particular case?
I started with reverse mode since that's the one with the eigen examples.

**Comment by allanleal** [comment]
The **forward mode** will most likely be the adequate algorithm for your case.

The reverse mode algorithm would be (not necessarily always, read below) more suitable if you had a scalar function `f`, such that after computing `y = f(x)`, where `y` is a scalar and `x = [x1, ..., xn]`, all derivatives `∂y/∂x1`, ..., `∂y/∂xn` can then be computed in a single pass. 

Note, however, that reverse mode algorithm requires the construction of an expression tree at **runtime time**, which implies in repeated _dynamic memory allocations_ as the tree is built during the evaluation of `f`. This tree is then subsequently used to compute the derivatives. 

This is in contrast with forward mode algorithm implemented in `autodiff`, which uses _template metaprogramming techniques_ to avoid temporary allocations and generating expression trees at **compile time** (which gives the chance to optimize/simplify this tree also at compile time).

Having said that, forward mode could still be a lot faster than reverse mode even for a scalar function `f` with many input variables `[x1, ..., xn]`. In the end, one needs to benchmark and see which mode has better performance in this case.

**Comment by allanleal** [comment]
I'm working on the computation of these higher-order derivatives. The implemented solution might be different than what initially stated above (tentatively without the need to define additional `dual` types for each scenario of higher-order derivative computations).

**Comment by versatran01** [comment]
Thanks for your answer. I will switch to forward mode then.

**Comment by versatran01** [comment]
And one quick question, does forward mode support eigen?

**Comment by allanleal** [comment]
Try:

~~~
VectorXdual f(const VectorXdual& x) {
    return x.cwiseProduct(x);
}

int main() 
{
    auto y = f(x);
    auto J = jacobian(f, y, x);

    std::cout << J std::endl;
}
~~~
The argument `y` will most likely disappear in future versions of function `jacobian`.

I'll add an example in README too once I finish the higher-order derivative support for forward mode.

**Comment by allanleal** [comment]
Hi @versatran01 , this feature has now been implemented and tested. Please check the documentation at https://autodiff.github.io and let me know if you have more questions. Check the Tutorials section BTW. There is an example there on the calculation of higher-order derivatives using forward mode.

You'll want to define a new dual type as follows:

```c++
#include <autodiff/forward.hpp>
using namespace autodiff;

// Define a 4th order dual type
using dual4th = HigherOrderDual<4>;

dual4th f(const dual4th& x, const dual4th& y)
{
    return sin(x) * cos(y);
}

int main() 
{
    dual4th x = 1.0;
    dual4th y = 2.0;

    // Calculate u = f(x, y)
    dual4th u = f(x, y);

    // Calculate d⁴u/dx²dy² 
    double uxxyy = derivative(f, wrt(x, x, y, y), x, y);
}
```
I'm writing this example from the top of my head - need to test, but this is the mechanics on how to compute higher-order derivatives using **autodiff** with the recent changes to the library.

**Comment by versatran01** [comment]
Thanks, I will try it out.
