### ISSUE TITLE
Gradient of General Function in Forward Mode

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#20]
In forward mode to take the gradient of a scalar you define some function `f` which returns a dual and takes in a `VectorXdual`

```cpp
dual f(const VectorXdual& x)
{
    // ...
}
```

The gradient is then taken with respect to another `VectorXdual`

```cpp
VectorXdual x = ...;
VectorXd dudx = gradient(f, x);
```

What happens if my function `f` needs to take in more than just a `VectorXdual`?

```cpp
dual f(const VectorXdual& x, double a, int b)
{
    // ...
}
```

How do I take the gradient then?

**Comment by kewp** [comment]
Does this look right?

```cpp
        VectorXd dwdu(m.nn*2);
        int i; for (i=0; i<2*m.nn; i++)
        {
            forward::seed(wrt(dof[i]));
            dwdu[i] = energy(m,D,dof).grad;
            forward::unseed(wrt(dof[i]));
        }
```

So I have a `VectorXdual dof` which contains all the degrees of freedom which I want derivatives in terms of. As you can see, my `energy` function takes in more than just those values...

**Comment by kewp** [comment]
Whilst writing up a complete code example I found how to do it. See the following:

```cpp

#include <iostream>
using namespace std;

#include <eigen3/Eigen/Core>
using namespace Eigen;

#include <autodiff/forward.hpp>
#include <autodiff/forward/eigen.hpp>
using namespace autodiff;

dual f(VectorXdual x, int n)
{
    dual t = 0.0;
    int i; for (i=0; i<n; i++)
        t += x[i];
    return t;
}

int main(int argc, char *argv[])
{
    int n = 5;
    VectorXdual x(n);
    int i; for (i=0; i<n; i++)
        x[i] = i;
    
    VectorXd dfdx(n);
    int j; for (j=0; j<n; j++)
    {
        seed(wrt(x[j]));
        dfdx[j] = f(x,n).grad;
        unseed(wrt(x[j]));
    }

    cout << dfdx << endl;
}
```

So I have a function `f` which takes in my variables `x` and a size parameter. The function itself just sums everything in `x`. In `main` I build up `x` as just numbers 0,1,2,3... etc. I then take the gradient of `f` with respect to each member of `x`.

This is my output:

```
1
1
1
1
1
```

That looks right - the derivative of (x0+x1+x2+...) with respect to x0, for example, is just 1.0.

**Comment by allanleal** [comment]
> What happens if my function f needs to take in more than just a VectorXdual?

If your function is:

~~~c++
dual f(const VectorXdual& x, double a, int b)
{
    // ...
}
~~~

you could create a lambda function, say, `fab`, and do:

~~~c++
double a = 1.0;
int b = 5;

auto fab = [=](const VectorXdual& x) { return f(x, a, b); };

VectorXdual x = ...;

VectorXd dudx = gradient(fab, x);
~~~

This avoids the whole for-loop and seeding/unseeding process that you presented earlier.

I'll open a new issue to (possibly) deprecate this form of `gradient` usage and replace with:

~~~c++
double a = 1.0;
int b = 5;
VectorXdual x = ...;

VectorXd dudx = gradient(f, wrt(x), x, a, b);
~~~

So, no need for intermediate lambda functions.
