### ISSUE TITLE
Higher-order derivs with reals

### ISSUE THREAD

**Issue by ianhbell** [autodiff/autodiff#201]
Following the discussion in #200 I have been trying to obtain higher-order pure derivatives with real types, and I can't figure out how to do it.

The example I tried to do is:
```c++
constexpr int Nderiv = 4;
double xdouble = 1.3;
autodiff::Real<Nderiv, double> x = xdouble;
auto f = [&](const auto& x_) -> autodiff::Real<Nderiv, double> { return sin(x_); };
auto ders = derivatives(f, wrt(x), at(x));
```
but it complains that I was trying to do cross derivative, but I wasn't.  The particular error message is:

```
1>C:\Users\ihb\Code\teqp\externals\autodiff\autodiff/forward/real/real.hpp(896,25): error C2338: Real<N, T> is optimized for higher-order **directional** derivatives. You're possibly trying to use it for computing higher-order **cross** derivatives (e.g., `derivative(f, wrt(x, x, y), at(x, y))`) which is not supported by Real<N, T>. Use Dual<T, G> instead (e.g., `using dual4th = HigherOrderDual<4>;`)
```

Also, I *think* it is the case that the eval() function isn't specialized for Real, which is essential for writing type-generic code.  It would also be sufficient if there was an ``isReal<T>`` constexpr function for type determination.

I guess I could in theory use the directional derivative function to do what I am trying to achieve, but that seems like a clunky approach in the higher-order-derivative context.

**Comment by ianhbell** [comment]
Note: ``along(1)`` in place of ``wrt(x)`` seems to do it.  But the comment about eval stands

**Comment by allanleal** [comment]
Hi Ian, please replace `at` by `along`, as you pointed our above. I think (can't check now) that `at` will only work with `autodiff::realNth` with the order is 1, in which case the a directional derivative along coordinate `x` is assumed.

As to `eval`, `autodiff::real` numbers do not produce compile time expressions like `autodiff::dual` numbers. What I mean here is that 

~~~cpp
real a = 1.0;
real b = 2.0;
auto c = a + 2*b;  // type of c is real, and not an expression SumExpr(a, MultExpr(2, b)) like when using dual
~~~

Thus, you should not need to worry about evaluating an expression when dealing with mathematical and arythimetic operations involving `autodiff::real` values.

**Comment by ianhbell** [comment]
P.S: Higher-order derivatives with reals are significantly faster than with duals.  5th derivative is 8 times faster than with dual in one test case

**Comment by allanleal** [comment]
> Right - eval() still needs a no-op branch for Real arguments though, even if you don't need to do anything with them.

I think so too. 

> P.S: Higher-order derivatives with reals are significantly faster than with duals. 5th derivative is 8 times faster than with dual in one test case

I was already expecting `real` to be faster than `dual` for this purpose, given that it was designed for this specific computation (higher-order directional derivatives). But the 8x speedup is a surprise! :)

It is not possible to bring `dual` (which others have already demonstrated to be fast compared to other codes) to be as fast as `real` for the same purpose. `dual` computes cross-derivatives, `real` does not.
