### ISSUE TITLE
Inverse trig functions applied to autodiff::real do not appear to propagate chain rule

### ISSUE THREAD

**Issue by rabraker** [autodiff/autodiff#205]
It seems as though the inverse trig functions for `autodiff::real` do not propagate their arguments derivatives properly. Consider the following example, which compares the result of differentiating the function `f(x) = asin(0.5*x)` for `real`, `dual` and numeric differentiation.

```
#include <iostream>
#include <cmath>

#include <autodiff/forward/real.hpp>
#include <autodiff/forward/dual.hpp>

namespace ad = autodiff;

template <typename T>
T asin_xby2(T x) {
  using std::asin;
  T z = x * 0.5;
  return asin(z);
}

int main() {
  const double x = 0.5;

  auto num_diff = [](auto func, double val) {
    const double eps = 1e-8;
    return (func(val + eps) - func(val)) / eps;
  };

  ad::dual xd(x);
  ad::real xr(x);
  const double d_asinxby2_numeric = num_diff(asin_xby2<double>, x);
  const double d_asinxby2_dual = ad::derivative(asin_xby2<ad::dual>, wrt(xd), at(xd));
  const double d_asinxby2_real = ad::derivative(asin_xby2<ad::real>, wrt(xr), at(xr));

  std::cout << "d/dx asin(0.5*x)|_{x=0.5}:"
            << ", numeric: " << d_asinxby2_numeric
            << ", autodiff dual= " << d_asinxby2_dual
            << ", autodiff real=" << d_asinxby2_real
            << "\n";
}
```
This results in 
```
>>> ./example
d/dx asin(0.5*x)|_{x=0.5}:, numeric: 0.516398, autodiff dual= 0.516398, autodiff real=1.0328
```

A few interesting things to note:
- If I use `sin` instead of `asin`, the results all agree. 
- If I only compute `asin(x)`, instead of `asin(0.5*x)`, the results agree.
-  I see similar problems using `atan` and `acos`, and similar agreement using `tan` and `cos`.
- Wrapping the constant in the type, e.g., `T z = x * T(0.5);` makes no difference.

These results used git hash `2fea1fd67840b3a1680c94b196e4ee93949f786e`, and were compiled with `g++ (Debian 8.3.0-6)`.

**Comment by allanleal** [comment]
Thanks for reporting this. I'm investigating what is going on. The derivatives computed in isolation works correctly, as you pointed out above. But in the context above, when `x` is multiplied by a `double`, something is happening with `asin`, `acos`, and `atan`.

**Comment by allanleal** [comment]
Release v0.6.6 now contains a fix for this issue. Thanks!

**Comment by rabraker** [comment]
Thanks for the super quick fix!
