### ISSUE TITLE
Cannot compile with Cmake 3.16.3

### ISSUE THREAD

**Issue by jefersonjlima** [autodiff/autodiff#223]
Hello,

I get some errors when I compile `autodiff` with `Cmake - version 3.16.3`. The `CMakeLists.txt` has the `cmake_minimum_required(VERSION 3.0)`, but, I think it isn't right. 

I compile with `Cmake 3.23.0` and it works fine.

**Comment by allanleal** [comment]
Hi @jefersonjlima . I was on vacation. Thanks for reporting this. Could you please let me know the exact error? With this info, I'll be able to identify the minimum cmake version (which is certainly not 3.0 indeed).

**Comment by jefersonjlima** [comment]
Hi @allanleal , I'm sorry about the delay.
I retest this issue in another machine and got the same error:

```
user:/tmp/autodiff/.build$ cmake --build . --target install
Scanning dependencies of target autodiff-cpptests
[  1%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/main.cpp.o
[  3%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/common/meta.test.cpp.o
[  4%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/dual/dual.test.cpp.o
[  6%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/dual/eigen.test.cpp.o
[  7%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/real/eigen.test.cpp.o
[  9%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/real/real.test.cpp.o
[ 10%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/utils/derivative.test.cpp.o
[ 12%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/utils/gradient.test.cpp.o
[ 13%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/forward/utils/taylorseries.test.cpp.o
[ 15%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/reverse/var/eigen.test.cpp.o
[ 16%] Building CXX object tests/CMakeFiles/autodiff-cpptests.dir/reverse/var/var.test.cpp.o
[ 18%] Linking CXX executable autodiff-cpptests
[ 18%] Built target autodiff-cpptests
Scanning dependencies of target autodiff4py
[ 19%] Building CXX object python/bindings/CMakeFiles/autodiff4py.dir/autodiff.py.cxx.o
[ 21%] Building CXX object python/bindings/CMakeFiles/autodiff4py.dir/dual.eigen.py.cxx.o
[ 22%] Building CXX object python/bindings/CMakeFiles/autodiff4py.dir/dual.py.cxx.o
[ 24%] Building CXX object python/bindings/CMakeFiles/autodiff4py.dir/real.eigen.py.cxx.o
[ 25%] Building CXX object python/bindings/CMakeFiles/autodiff4py.dir/real.py.cxx.o
[ 27%] Linking CXX shared module autodiff4py.cpython-38-x86_64-linux-gnu.so
[ 27%] Built target autodiff4py
Scanning dependencies of target autodiff-setuptools
CMake Error: cmake version 3.16.3
Usage: /usr/bin/cmake -E <command> [arguments...]
Available commands:
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files [--ignore-eol] file1 file2
                              - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory <dir>... - remove directories and their contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch <file>...           - touch a <file>.
  touch_nocreate <file>...  - touch a <file> but do not create it.
  create_symlink old new    - create a symbolic link new -> old
  true                      - do nothing with an exit code of 0
  false                     - do nothing with an exit code of 1

make[2]: *** [python/package/CMakeFiles/autodiff-setuptools.dir/build.make:60: python/package/CMakeFiles/autodiff-setuptools] Error 1
make[1]: *** [CMakeFiles/Makefile2:382: python/package/CMakeFiles/autodiff-setuptools.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

It is fixed when I updated the `cmake` to `version 3.23.1`.

**Comment by allanleal** [comment]
It should be possible now to compile with CMake 3.16. Thanks for reporting.

**Comment by rmslick** [comment]
@allanleal I am  experiencing this issue and I cloned today. Any updates?

**Comment by allanleal** [comment]
@rmslick what is the error message? What is your cmake version?

**Comment by rmslick** [comment]
@allanleal Version is 3.16.3. Error posted below. Thanks for the quick reply! 


[ 41%] Built target autodiff4py
Scanning dependencies of target autodiff-setuptools
CMake Error: cmake version 3.16.3
Usage: /usr/bin/cmake -E <command> [arguments...]
Available commands: 
  capabilities              - Report capabilities built into cmake in JSON format
  chdir dir cmd [args...]   - run command in a given directory
  compare_files [--ignore-eol] file1 file2
                              - check if file1 is same as file2
  copy <file>... destination  - copy files to destination (either file or directory)
  copy_directory <dir>... destination   - copy content of <dir>... directories to 'destination' directory
  copy_if_different <file>... destination  - copy files if it has changed
  echo [<string>...]        - displays arguments as text
  echo_append [<string>...] - displays arguments as text but no new line
  env [--unset=NAME]... [NAME=VALUE]... COMMAND [ARG]...
                            - run command in a modified environment
  environment               - display the current environment
  make_directory <dir>...   - create parent and <dir> directories
  md5sum <file>...          - create MD5 checksum of files
  sha1sum <file>...         - create SHA1 checksum of files
  sha224sum <file>...       - create SHA224 checksum of files
  sha256sum <file>...       - create SHA256 checksum of files
  sha384sum <file>...       - create SHA384 checksum of files
  sha512sum <file>...       - create SHA512 checksum of files
  remove [-f] <file>...     - remove the file(s), use -f to force it
  remove_directory <dir>... - remove directories and their contents
  rename oldname newname    - rename a file or directory (on one volume)
  server                    - start cmake in server mode
  sleep <number>...         - sleep for given number of seconds
  tar [cxt][vf][zjJ] file.tar [file/dir1 file/dir2 ...]
                            - create or extract a tar or zip archive
  time command [args...]    - run command and display elapsed time
  touch <file>...           - touch a <file>.
  touch_nocreate <file>...  - touch a <file> but do not create it.
  create_symlink old new    - create a symbolic link new -> old
  true                      - do nothing with an exit code of 0
  false                     - do nothing with an exit code of 1

make[2]: *** [python/package/CMakeFiles/autodiff-setuptools.dir/build.make:60: python/package/CMakeFiles/autodiff-setuptools] Error 1
make[1]: *** [CMakeFiles/Makefile2:384: python/package/CMakeFiles/autodiff-setuptools.dir/all] Error 2
make: *** [Makefile:130: all] Error 2

**Comment by allanleal** [comment]
OK, sounds like 3.16.3 is not the minimum required but some more recent version. Please update cmake or use a newer version.

**Comment by rmslick** [comment]
I wish I saw your edit before reading your uncrossed out advice. I upgraded to 3.23 and got smashed with errors when running  cmake --build . --target install. They are too long to post in-full but here is the end:

  843 |     return std::forward<L>(l) + ( -std::forward<R>(r) );
      |            ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp: In instantiation of ‘C_A_T_C_H_T_E_S_T_0()::<lambda(const auto:15&, const auto:16&)> [with auto:15 = autodiff::detail::Dual<double, double>; auto:16 = autodiff::detail::Dual<double, double>]’:
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp:719:30:   required from ‘C_A_T_C_H_T_E_S_T_0()::<lambda(const auto:17&, const auto:18&)> [with auto:17 = autodiff::detail::Dual<double, double>; auto:18 = autodiff::detail::Dual<double, double>; autodiff::dual = autodiff::detail::Dual<double, double>]’
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp:722:9:   required from here
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp:714:48: error: invalid use of void expression
  714 |             return 100.0 * pow2(x*x - y) + pow2(1.0 - x);
      |                                            ~~~~^~~~~~~~~
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp: In instantiation of ‘C_A_T_C_H_T_E_S_T_0()::<lambda(const auto:17&, const auto:18&)> [with auto:17 = autodiff::detail::Dual<double, double>; auto:18 = autodiff::detail::Dual<double, double>; autodiff::dual = autodiff::detail::Dual<double, double>]’:
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp:722:9:   required from here
/home/rmslick/autodiff/tests/forward/dual/dual.test.cpp:719:30: error: could not convert ‘(& rosenbrock)->C_A_T_C_H_T_E_S_T_0()::<lambda(const auto:15&, const auto:16&)>((* & x), (* & y))’ from ‘void’ to ‘autodiff::dual’ {aka ‘autodiff::detail::Dual<double, double>’}
  719 |             return rosenbrock(x, y);
      |                    ~~~~~~~~~~^~~~~~
      |                              |
      |                              void
make[2]: *** [tests/CMakeFiles/autodiff-cpptests.dir/build.make:104: tests/CMakeFiles/autodiff-cpptests.dir/forward/dual/dual.test.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:283: tests/CMakeFiles/autodiff-cpptests.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

**Comment by allanleal** [comment]
What is the compiler and version you're using? As you can see in the [past GitHub Actions](https://github.com/autodiff/autodiff/actions), the build process is working correctly for Linux, Windows and macOS.

**Comment by rmslick** [comment]
@allanleal I must have messed something up when I switched CMake versions. I uninstalled cmake and reinstalled 3.16.3 and rebuilt succesffuly. Thanks a lot!
