### ISSUE TITLE
Breaking change 

### ISSUE THREAD

**Issue by artivis** [autodiff/autodiff#233]
Commit 7b2bd6315632ab3d142c30b11a62b072afb5f4c3 introduced a breaking change that impacts custom vector types which might provide the `[](int)` operator but not `()(int)` - as in e.g. [`manif`](https://github.com/artivis/manif) ([failing job example](https://github.com/artivis/manif/runs/7154169301?check_suite_focus=true)).

```terminal
/usr/local/include/autodiff/forward/utils/gradient.hpp:70:28: error: no match for call to ‘(manif::Rn<autodiff::detail::Dual<double, double>, 2>) (int&)’
   70 |                 f(i++, item(j)); // call given f with current index and variable from item (a vector)
      |                        ~~~~^~~
```

**Comment by allanleal** [comment]
Hi @artivis . I'm on vacation (July) and cannot act on this now. Would you please find a general solution (and provide a PR) or maybe consider implementation of `()(int)` operator on your side (`manif` lib)?

**Comment by artivis** [comment]
I've opened #234.
