### ISSUE TITLE
Support for user defined functions

### ISSUE THREAD

**Issue by hantunes-uk** [autodiff/autodiff#239]
### Discussed in https://github.com/autodiff/autodiff/discussions/225

<div type='discussions-op-text'>

<sup>Originally posted by **hantunes-uk** April 20, 2022</sup>
Hi,

First of all superb library!
One thing I would like to know is if it is possible to add a custom functions (possibly with state) and if so how? I have 2 cases:

- first one is the Gauss cdf for which we have a "complex" approximation that is machine precision but for which we know the pdf analytically.  Note that in our implementation this Gauss class has 2 parameters (mean and std dev).
- second one is we use a 3rd party library for one dimensional interpolation. It is done via instantiation of an Interpolant class initialized early on. This class has 2 methods, one called value which computes the interpolated value for a given input x the other is derivatives which computes derivatives of the interpolator up to second order in x. 

The idea would for me to create some wrapper classes/functions that make these functions combine with autodiff. when computing derivatives. 

Thanks very much in advance.
 </div>

**Comment by allanleal** [comment]
Sorry, it's difficult for me to give support and advice on very specific `autodiff` use cases. I hope you have figured out a solution by checking all examples.
