### ISSUE TITLE
Revert required version of cmake

### ISSUE THREAD

**Issue by ianhbell** [autodiff/autodiff#240]
Probably related to: https://github.com/autodiff/autodiff/issues/223 .  Please revert the minimum required version of cmake to 3.16. Otherwise with required version set to 22.04, does not compile on base ubuntu 20.04 image, because ubuntu 20.04 provides 3.16.13 .  But it does compile fine if I just set the required version to 3.16 in autodiff.

**Comment by allanleal** [comment]
Hi Ian, thanks for this. [This commit](https://github.com/autodiff/autodiff/commit/5a8501f36b537a0663105b1288f29801dec495a6) fixes this.
