### ISSUE TITLE
Catch2 v3

### ISSUE THREAD

**Issue by RMeli** [autodiff/autodiff#246]
Hello. I was trying to build `autodiff` locally where I have Catch2 v3 installed and realized that `autodiff` is still using Catch v2. Is there any interest or plan to migrate to Catch v3, now that it's been [officially released](https://github.com/catchorg/Catch2/releases/tag/v3.0.1)?

I did the migration on [my fork](https://github.com/RMeli/autodiff/tree/catch2-v3), and everything seems to work well. I can open a PR if this is of interest at all.

**Comment by allanleal** [comment]
Hi @RMeli , yes, that would be great. Thanks for helping with the project.
