### ISSUE TITLE
Conda development environment installation instructions

### ISSUE THREAD

**Issue by RMeli** [autodiff/autodiff#247]
The `environment.devenv.yaml` file contains
```
{% set python_version = os.environ.get("PYTHON_VERSION", "3.9") %}
```
which makes the following fail:
```
conda env create -f environment.devenv.yaml
```

I think it would be great to add https://github.com/autodiff/autodiff/issues/166#issuecomment-875805243 to the [installation instructions](https://autodiff.github.io/installation/), so that it becomes clearer that `conda-devenv` should be used to build the development environment from `environment.devenv.yaml`.

**Comment by allanleal** [comment]
Thanks for the PR!
