### ISSUE TITLE
Max function broadcast support 

### ISSUE THREAD

**Issue by i-abr** [autodiff/autodiff#257]
Hi, 

I just came across an issue where I am trying to create a ReLU `max` function in the following way 
```
real func(const ArrayXreal& x) { 
    return max(0, x).sum()
}
```

however, this code is not compiling with the error `no matching function for call to 'max'`.  I do see a candidate template `constexpr auto max(const Real<N, T>& x, const U& y)` and `constexpr auto max(const U& x, const Real<N, T>& y)` in `real.hpp`, but unsure how to fix. I suspect this may have to do with broadcasting the scalar input `0` to the array, but I did try with an Eigen zero array and that also did not work. Please advise. 

Note that `pow(tanh(x),2).sum()` works if I replace the `max(0,x).sum()` code. 

Any help is appreciated! 
Thank you!

**Comment by allanleal** [comment]
This should use (not tested): `x.max(0.0).sum()`. Please check [Eigen documentation on Array](http://eigen.tuxfamily.org/dox/group__QuickRefPage.html#title6).
