### ISSUE TITLE
How to convert a MatrixXdual to MatrixXd? 

### ISSUE THREAD

**Issue by AzureViolin** [autodiff/autodiff#26]
I'm expecting something like:

```
MatrixXdual mat_dual;
MatrixXd mat_d = val(mat_dual);
```

However apparently val() can only be applied to dual, rather than any container of dual. Is there an existing way to do that?

Also, it took me quite a while to figure out how to do jacobian on multi-vector-variable function and conversion between dual and double, the readme should be updated. I can help if you want.

**Comment by allanleal** [comment]
Hi. For the conversion between `dual` and `double` matrices, I think you can rely on the `cast` method of Eigen. Could you please try:

~~~c++
MatrixXdual mat_dual;
MatrixXd mat_double = mat_dual.cast<double>();
~~~

and let me know?

> Also, it took me quite a while to figure out how to do jacobian on multi-vector-variable function and conversion between dual and double, the readme should be updated. I can help if you want.

That would be great! Just open a PR when you can. Thanks a lot in advance.

**Comment by AzureViolin** [comment]
Finally got time to get back to this, sorry for being late. 
I've tried cast back then and it doesn't work or have too much restrictions, can't really recall the exact issue with cast. I've created dedicated functions to solve my problem. Probably too rudimentary to be added into your implementation.  
```
//convert MatrixXdual to MatrixXd
MatrixXd mat_dual2d(const MatrixXdual& mat_dual){
  MatrixXd mat_d;
  for (size_t j = 0, nRows = mat_dual.rows(), nCols = mat_dual.cols(); j < nCols; ++j)
    for (size_t i = 0; i < nRows; ++i)
      mat_d(i,j) = val(mat_dual(i,j));
  return mat_d;
}

VectorXd vec_dual2d(const VectorXdual& vec_dual){
  size_t nRows = vec_dual.rows();
  VectorXd vec_d(nRows);
  //cout<<"vec_dual rows "<<nRows<<endl;
  for (size_t i = 0; i < nRows; ++i)
    vec_d(i) = val(vec_dual(i));
  return vec_d;
}
```

**Comment by AzureViolin** [comment]
Regarding the multi variable jacobian, I don't know how to add a new item to your tutorial. 
[https://autodiff.github.io/tutorials/#jacobian-of-a-vector-function](url)
Specifically, I'd like to add a section after:
> Jacobian of a vector function

And call it

> Jacobian of a multi-vector function

Then attached with a section of code. Could you point me to which file I should change? I can then go ahead change it and do a PR.

**Comment by allanleal** [comment]
Eigen is probably not casting because it might have some casting requirements on the custom scalar type that is still not implemented. Would you kindly check the error message and also Eigen casting requirements so that this works using `Eigen::Matrix::cast` method?

As to the tutorial, I propose we discuss this in a new issue. Would you please initiate open a new issue and discuss (briefly) about the tutorial (with explanation about this multi-vector function)?

**Comment by AzureViolin** [comment]
I might not have time for the cast thing yet, but will come back to this when I've got enough time. Sorry for that.

**Comment by ludkinm** [comment]
Hi, I've had the same issue.

Compiling this MWE leads to the error: 
```
Eigen/src/Core/MathFunctions.h:382:12: error: invalid static_cast from type ‘const autodiff::forward::Dual<double, double>’ to type ‘double’
     return static_cast<NewType>(x);
```
So ``Eigen`` calls ``static_cast``.

On fix for this to give an explicit conversion from ``Dual<T,G>`` to type ``T``.

I'll make a pull request to add a fix

**Comment by allanleal** [comment]
I'll close this issue, since this has been recently fixed (with a fix provided by @ludkinm ). Please re-open if needed.
