### ISSUE TITLE
cmake error: install DIRECTORY given no DESTINATION!

### ISSUE THREAD

**Issue by andyyankai** [autodiff/autodiff#28]
cmake .. -DCMAKE_INSTALL_PREFIX=/some/local/dir
CMake Error at CMakeLists.txt:20 (install):
  install DIRECTORY given no DESTINATION!

CMake Warning (dev) in CMakeLists.txt:
  No cmake_minimum_required command is present.  A line of code such as

    cmake_minimum_required(VERSION 3.10)

  should be added at the top of the file.  The version specified may be lower
  if you wish to support older CMake versions for this project.  For more
  information run "cmake --help-policy CMP0000".
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Configuring incomplete, errors occurred!
See also "/mnt/d/research/Shuang/auto_diff/autodiff/autodiff/CMakeFiles/CMakeOutput.log".

**Comment by andyyankai** [comment]
My bad, the build is in incorrect place

**Comment by printablealice** [comment]
Had same issue.  To install you should run the _Installation using CMake_ commands from the same directory that contains README.md
