### ISSUE TITLE
osx-arm64  / linux-aarch64 build missing on conda-forge

### ISSUE THREAD

**Issue by briha** [autodiff/autodiff#289]
The builds available on conda-forge do not include builds targetting `osx-arm64` or `linux-aarch64`. I would appreciate it if those target architectures could be added. `osx-arm64`, at least, is used quite widely.

**Comment by allanleal** [comment]
There is a [conda-forge PR](https://github.com/conda-forge/autodiff-feedstock/pull/49) to create the osx-arm64 packages, but all such builds are failing. The error seems to come from the use of the Catch2 library in osx-arm64. Would you be able to investigate this?

**Comment by briha** [comment]
I'm not really familiar with conda-build, but sure, I'll have a look as soon as I get to it!

**Comment by allanleal** [comment]
You actually do not need to deal with conda-forge/conda-build now. Just compiling autodiff in your system and checking if the same Catch2 build failure happens would be enough (and then trying to see a solution for this in your machine). Once I know the solution, I can do the rest.

**Comment by briha** [comment]
It compiled without any issues on my system, so unfortunately, not really helpful for debugging. Judging from that, I think it's probably something with the cross-compilation that is going wrong.

**Comment by briha** [comment]
I think the macOS SDK used is just too old, and doesn't support aarch64 yet.

From the Azure build:
```/Applications/Xcode_13.2.1.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/usr/include/sys/cdefs.h:784:2: error: Unsupported architecture```


The relevant lines in `cdefs.h` are ([in the 10.14 SDK](https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX10.14.sdk/usr/include/sys/cdefs.h#L778-L785)):
```c
/*
 * Architecture validation for current SDK
 */
#if !defined(__sys_cdefs_arch_unknown__) && defined(__i386__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__x86_64__)
#else
#error Unsupported architecture
#endif
```


Whereas in [newer ones](https://github.com/phracker/MacOSX-SDKs/blob/041600eda65c6a668f66cb7d56b7d1da3e8bcc93/MacOSX11.3.sdk/usr/include/sys/cdefs.h#L820-L829), it includes arm as a valid option: 
```c
/*
 * Architecture validation for current SDK
 */
#if !defined(__sys_cdefs_arch_unknown__) && defined(__i386__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__x86_64__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__arm__)
#elif !defined(__sys_cdefs_arch_unknown__) && defined(__arm64__)
#else
#error Unsupported architecture
#endif
```

so updating that may be all that is needed.

**Comment by briha** [comment]
Update: I just gave it a try, following the conda-forge [guide](https://conda-forge.org/blog/posts/2020-10-29-macos-arm64/) for osx-arm64. I could reproduce the error with the MacOSX10.14 SDK on a linux host, and it seems to compile when using MacOSX11.3.sdk instead (I only tried `osx_arm64_python3.8.____cpython`).

**Comment by allanleal** [comment]
Thanks for investigating this. We need to check if conda-forge supports the MacOSX11.3 SDK.

**Comment by briha** [comment]
It built with 11.0 (https://github.com/conda-forge/autodiff-feedstock/pull/52), which is, as far as I understand, the first one supporting Aarch64 – so I think, unless I overlooked something, this should solve it.

**Comment by allanleal** [comment]
Yes, I just realized that you created that conda-forge PR for autodiff-feedstock. Just merged it. I'll investigate later if the tests can be reactivated for the osx-arm64 builds, given that the v11.0 SDK is specified for this case. Thanks for helping with this!
