### ISSUE TITLE
Is non-const argument in `gradient` necessary?

### ISSUE THREAD

**Issue by agtumulak** [autodiff/autodiff#296]
https://github.com/autodiff/autodiff/blob/0b340bc8f8f7b3b7c4ce242a51971831265191b5/autodiff/reverse/var/eigen.hpp#L121

I am interested in giving `gradient` a view to a `const` vector of independent variables but the function signature seems to require a non-const `Eigen::DenseBase&`. Can this be safely converted to

```cpp
 auto gradient(const Variable<T>& y, const Eigen::DenseBase<X>& x) 
```

**Comment by allanleal** [comment]
Hi @agtumulak , this is needed because `gradient` needs to seed the entries in `x` to perform the derivatives.
