### ISSUE TITLE
Readme is a bit out-dated

### ISSUE THREAD

**Issue by versatran01** [autodiff/autodiff#3]
For example, it feels like that the eigen stuff should be used with include instead of define?

**Comment by allanleal** [comment]
Yes, the README does not yet represent fully some changes made after introduction of forward mode derivatives. I'll update it soon.

**Comment by allanleal** [comment]
Hi @versatran01 . Please check the website https://autodiff.github.io that should fix this issue for now. 

If you have more specific documentation needs, please submit a new issue. Thanks for the feedback.
