### ISSUE TITLE
Gitter link on website

### ISSUE THREAD

**Issue by osorensen** [autodiff/autodiff#304]
Just a heads up: I wonder if the website has not been rebuilt after the [PR removing Gitter link](https://github.com/autodiff/autodiff/commit/247620ddc19be689e7f122ec914b4b3f9e95aeb3). The bottom of the website still looks as follows:

<img width="768" alt="image" src="https://github.com/autodiff/autodiff/assets/21175639/9ca3fffb-5280-43dc-b0bb-59149f3ac6de">

**Comment by allanleal** [comment]
Thanks for the heads-up. I'll update the website shortly.

**Comment by allanleal** [comment]
Fixed! Thanks again for reporting.
