### ISSUE TITLE
[feature] GPU support

### ISSUE THREAD

**Issue by JieRen98** [autodiff/autodiff#308]
Greetings,

I am trying to use `autodiff` in my CUDA codes. Consider the simple code snippet below:
```cuda
__global__ void fn(real *x, real *y, real *z) {
  auto tid = threadIdx.x + blockIdx.x * blockDim.x;
  z[tid] = x[tid] * y[tid];
}
```

The compiler gives the error:
```
candidate function not viable: call to __host__ function from __global__ function
```
The most straightforward method is to change `operator*`'s signature to:
```cpp
template<size_t N, typename T>
#ifdef __CUDACC__
__host__ __device__
#endif
auto
operator*(Real<N, T> x, const Real<N, T>& y)
{
    return x *= y;
}
```
Of course, other changes need to be adapted.

This is only the first step, to explore GPU's acceleration better, we also need to think about the data structure and rewrite functions like `ForEachWrtVar`

I have also done some tries in my previous project: https://link.springer.com/chapter/10.1007/978-3-031-19836-6_40. I feel my way is still not elegant enough and happily I found your project could be very helpful. I have some raw ideas for adapting `autodiff` to GPU, if you are interested please drop me an email for further discussion: Jie.Ren@kaust.edu.sa

My goal is to make `autodiff` support GPU & CPU vectorization operations elegantly, then I can import `autodiff` into my project rather than reinvent the wheel in an ugly way.

Best,
Jie

**Comment by allanleal** [comment]
Hi @JieRen98 , thanks for your interest and sharing ideas here on making autodiff GPU enabled. I'll be happy to review a pull request with the necessary changes to accommodate compilation using CUDA/OpenCL.

**Comment by JieRen98** [comment]
> Hi @JieRen98 , thanks for your interest and sharing ideas here on making autodiff GPU enabled. I'll be happy to review a pull request with the necessary changes to accommodate compilation using CUDA/OpenCL.

Please check PR: https://github.com/autodiff/autodiff/pull/309
