### ISSUE TITLE
Derivative wrt x returns nan, but function does not depend on x at all.

### ISSUE THREAD

**Issue by cstroessner** [autodiff/autodiff#315]
In the following code snippet, I would expect that the derivative with respect to x of f(x) = -5^5 is equal to zero. However, this is not the case. It returns nan instead. Is this behavior intentional?

```
   autodiff::real x = 0;
   auto fun = [&](autodiff::real x) -> autodiff::real
   {
      return pow(autodiff::real(-5), autodiff::real(5)); // does not depend on x
   };
   autodiff::real dx = autodiff::derivative(fun, autodiff::detail::wrt(x), autodiff::at(x));
   // dx.val() is nan, but it should be zero
```

Investigation: Computing the derivative of -5^y with respect to y should give nan. I believe the issue is caused by storing a nan in the derivative of autodiff::real(5), but I am not sure why and where this affects the derivative with respect to x.

Further remarks: While it might seem strange at first to pass autodiff::real arguments to pow, this is something I cannot avoid in my application. In case this behavior is intentional, is there any workaround to still create the autodiff::real arguments inside of fun? Would it, for instance, be possible to explicitly state that the derivatives of these arguments should not be tracked?

**Comment by allanleal** [comment]
Hi @cstroessner , this is because there is a log evaluation at -5 when doing `pow(x, y)` with `x = -5` and `y`. This creates the `nan`. See algorithm below:

https://github.com/autodiff/autodiff/blob/main/autodiff/forward/real/real.hpp#L467

~~~c++
template<size_t N, typename T>
constexpr auto pow(const Real<N, T>& x, const Real<N, T>& y)
{
    Real<N, T> res;
    res[0] = pow(x[0], y[0]);
    if constexpr (N > 0)
    {
        // assert(x[0] != 0 && "autodiff::pow(x, y) has undefined derivatives when x = 0");
        if(x[0] == 0) return res;
        Real<N, T> lnx = log(x);
        Real<N, T> a;
        For<1, N + 1>([&](auto i) constexpr {
            a[i] = Sum<0, i + 1>([&](auto j) constexpr {
                constexpr auto c = BinomialCoefficient<i.index, j.index>;
                return c * y[i - j] * lnx[j];
            });

            res[i] = Sum<0, i>([&](auto j) constexpr {
                constexpr auto c = BinomialCoefficient<i.index - 1, j.index>;
                return c * a[i - j] * res[j];
            });
        });
    }
    return res;
}
~~~

If `y` in `pow(x, y)` is always an integer, perhaps you could define your own pow function that only uses multiplication. In any case, please study the implementation above to better understand why `nan` is produced and perhaps how to circumvent it.

**Comment by cstroessner** [comment]
Dear @allanleal, I agree that pow(a,b) should lead to nan in the derivative of b. But why does the nan in the derivative of b affect the derivative with respect to x in my example?

For clarification my function is f(x) = -3125. And the constant -3125 is computed as pow(-5,5) when evaluating f(x).

**Comment by allanleal** [comment]
In the line of code, `Real<N, T> lnx = log(x);`, we see that `log(-5)` will be evaluated. When this happens, any operation with `lnx` will be infected with `nan`. I can't check this in more detail at the moment. Suggest that you find an alternative solution or propose a change in the algorithm. We can't avoid the need for `log`. Also, not sure why you have to evaluate `pow(-5, 5)` using `autodiff::real`.
