### ISSUE TITLE
CUDA: thrust::reduce fails for autodiff::real

### ISSUE THREAD

**Issue by satfra** [autodiff/autodiff#316]
Hello,

The following code succeeds to compile, but thrust throws an error after the reduction:
`main.cu`:
```C++
#include <autodiff/forward/real.hpp>
#include <autodiff/forward/dual.hpp>
#include <thrust/device_vector.h>
#include <thrust/reduce.h>
#include <thrust/execution_policy.h>
#include <iostream>

int main()
{
  using NT = autodiff::real;
  thrust::device_vector<NT> device_data({1.,2.,3.});
  const NT out = thrust::reduce(thrust::device, device_data.begin(), device_data.end(), NT(0.), thrust::plus<NT>());
  std::cout << out << std::endl;
  return 0;
}
```
`CMakeLists.txt`:
```CMake
cmake_minimum_required(VERSION 3.18)

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED On)
project(CUDA_testing LANGUAGES CXX CUDA)

set(CUDA_NVCC_FLAGS "${CUDA_NVCC_FLAGS} $ENV{CUDA_NVCC_FLAGS} -lineinfo --default-stream per-thread --expt-relaxed-constexpr --extended-lambda")
find_package (Eigen3 REQUIRED)
link_libraries(Eigen3::Eigen)
include_directories(SYSTEM ${CMAKE_SOURCE_DIR}/../../../external/autodiff)

add_executable(main main.cu)
set_target_properties(main PROPERTIES CUDA_SEPARABLE_COMPILATION ON)
```

Thrust fails the reduction with the error
```
CUDA error 719 [/opt/cuda/bin/../targets/x86_64-linux/include/cub/util_device.cuh, 510]: unspecified launch failure
terminate called after throwing an instance of 'thrust::system::system_error'
  what():  reduce failed to synchronize: cudaErrorLaunchFailure: unspecified launch failure
```

My other kernels using autodiff::real work in the same setup without an issue. Running this through gdb leads me to `thrust/system/cuda/detail/reduce.h:980`, which is basically the final synchronization call after the reduction. 
I am running this on a RTX3080 under Linux with CUDA 12.3.103.

Interestingly, if I use 
```C++
  using NT = autodiff::dual;
```
the code runs without any issue and produces the correct output.

**Comment by allanleal** [comment]
GPU support was implemented by @JieRen98 - could you please check this?

**Comment by JieRen98** [comment]
Ok, checking it

**Comment by JieRen98** [comment]
Please try to use `add_subdirectory()` for importing autodiff and try to use `target_link_libraries(... autodiff::autodiff ...)` for linking against it.

Best,
Jie

**Comment by JieRen98** [comment]
> Please try to use `add_subdirectory()` for importing autodiff and try to use `target_link_libraries(... autodiff::autodiff ...)` for linking against it.
> 
> Best, Jie

In such a way, it works without any errors on my laptop (RTX 3060, CUDA 12.3.107).

**Comment by JieRen98** [comment]
Here is an example:
Assuming your working space would look like this:
```
.
├── autodiff
├── build
├── CMakeLists.txt
└── main.cu
```
Use `CMakeLists.txt` in my way:
```cmake
cmake_minimum_required(VERSION 3.18)

set(CMAKE_CXX_STANDARD 20)
project(CUDA_testing LANGUAGES CXX CUDA)

add_subdirectory(autodiff)
find_package(Eigen3 REQUIRED)

add_executable(main main.cu)
target_link_libraries(main PUBLIC Eigen3::Eigen autodiff::autodiff)
```

Then everything works smoothly.

Best,
Jie

**Comment by satfra** [comment]
Indeed, this fixes it. Up until now I thought I could use autodiff as a header-only library, guess that's not entirely true. Thanks a lot!

**Comment by JieRen98** [comment]
Let me think about how to make it header-only later, anyway, thanks.
