### ISSUE TITLE
`dual` and `real`, what's the difference?

### ISSUE THREAD

**Issue by xchern** [autodiff/autodiff#322]
`dual` and `real` type are used with forward-mode in [the teaser picture](https://github.com/autodiff/autodiff/raw/main/art/autodiff-header.svg), but I can not find an explaination in documents. The two types both consist of two doubles, and have same API usage. So I'm really confused why two types are constructed instead of only one?

**Comment by xchern** [comment]
got the answer [here](https://autodiff.github.io/tutorials/#higher-order-cross-derivatives-of-a-scalar-function)

it seems that the two only diff if used with higher-order derivatives

> /*-------------------------------------------------------------------------------------------------
> === Note ===
> ---------------------------------------------------------------------------------------------------
> In most cases, dual can be replaced by real, as commented in other examples.
> However, computing higher-order cross derivatives has definitely to be done
> using higher-order dual types (e.g., dual3rd, dual4th)! This is because real
> types (e.g., real2nd, real3rd, real4th) are optimally designed for computing
> higher-order directional derivatives.
> -------------------------------------------------------------------------------------------------*/

**Comment by allanleal** [comment]
> it seems that the two only diff if used with higher-order derivatives

Yes, real is optimized for derivatives along a direction at higher orders. dual can be used for all cross derivatives at higher orders. 

For 1st order derivatives, both number types produce derivatives "along the same direction", i.e., along the change of the variable for which the derivative is being computed.
