### ISSUE TITLE
Support for complex and matrices

### ISSUE THREAD

**Issue by davidleitao95** [autodiff/autodiff#35]
Hi! 

I was wondering if you plan to support complex duals in the future? I wanted to use your library, but this would be a big requirement for me. 

Thanks for this amazing work! Cheers,
David

**Comment by davidleitao95** [comment]
Sorry, noticed that matrices are already support

**Comment by allanleal** [comment]
Hi @davidleitao95 . `std::complex` is a template type; I never tried, but I think you could do:

~~~c++
using cxdual = std::complex<autodiff::dual>
~~~

and then use `cxdual` throughout. 

I think it would be amazing, and I would deeply appreciate, if you could try this and prepare a simple tutorial (like the existing ones) showing the use of `autodiff::dual` with `std::complex`.

**Comment by davidleitao95** [comment]
Thanks for the tip!  I'll give it a go when I have a bit more time and let you know.

A bit off topic, but right now I am using autodiff to try accelerating an optimization where my cost function depends on hundreds of input variables. Firstly I used the forward mode (erroneously) just to confirm the run-time was very big. Then, I implemented with the reverse mode, as for this one I was expecting the run-time to be smaller. It happens that even when using just 6 input variables, the run-time to calculate the gradient is ~15 seconds, while a simple cost function evaluation is <0.01 seconds. Any ideas where the algorithm might be doing unnecessary calculations?

Thanks for all the help. Cheers,
David

**Comment by allanleal** [comment]
Are you compiling in Release or Debug mode?

**Comment by davidleitao95** [comment]
I'm compiling in release mode. I noticed that it is in the gradient calculation that it is taking almost all time.
Besides the design variables, my cost function receives some parameters which I pass as 'const VectorXd& double' to avoid the 'gradient' function calculating the derivatives wrt them. Not sure if this affects the gradient calculation anyway.

**Comment by allanleal** [comment]
Thanks for the information. May I ask you to open a new issue in which a small example more or less demonstrating your use case is given? I must say though that lately only the forward mode algorithm has received more attention, because it is what I have been using in my research, but I'll be happy to have a look at this and improve sub optimal performance.
