### ISSUE TITLE
Can't extract a value as double from an VectorXdual

### ISSUE THREAD

**Issue by nestabentum** [autodiff/autodiff#36]
I'm trying to calculate the jacobian of a given vector function - for that I kept pretty close to the tutorial **Jacobian of a vector function**. Everything seems to work fine except for the conversion of values extracted from a VectorXdual - I've tried access via **()**, **[]** or **coeff()** I've received dual  or scalar objects from these methods but never double values. I've tried casting the duals or scalars to double but unfortunately that did not work for me - What is the ideal process of extraction/conversion here?

**Comment by davidleitao95** [comment]
You have to call the function _.val_. For example:
dual x;
double a = x.val;

**Comment by allanleal** [comment]
Hi @nestabentum - could you please post here a very minimal example of what you are trying to do? I'm not sure if you want to convert `VectorXdual` to `VectorXd` or just a `dual` entry of this vector to `double`, in which case @davidleitao95 above makes a good suggestion.

**Comment by nestabentum** [comment]
@allanleal I wanted to convert a dual entry of an `VectorXdual` to `double` so @davidleitao95 's suggestion worked great for me - thanks a lot!
