### ISSUE TITLE
Problems Installing and linking with Eigen

### ISSUE THREAD

**Issue by dmckinnell** [autodiff/autodiff#43]
None of the CMakeList files contain a command to find the Eigen package so the final installation command fails unless the files are altered. The example files that use the Eigen directories have an issue in the include command #include <eigen3/Eigen/Core> should just be #include <Eigen/Core>.

**Comment by allanleal** [comment]
I see. I'll see if I can fix this now, adding `find_package(Eigen REQUIRED)` and propagate Eigen dependency to targets linking against `autodiff`.

**Comment by allanleal** [comment]
Note that `eigen3/Eigen/Core` is the path one would use if `conda` is being used to install autodiff or if Eigen was installed using its `cmake` + `make install`.

**Comment by pariterre** [comment]
I was about to open the same issue. 
I think referencing directly ```eigen3/Eigen/Core``` as the path is not the proper way to do since FindEigen is supposed to give you the path to ```eigen3``` already. Therefore the include should read ```Eigen/Core```.

**Comment by allanleal** [comment]
@pariterre Thanks for the explanation and apologies for the delay (I'm on vacation). What you say makes sense then to change `eigen3/Eigen/Core` occurrences to `Eigen/Core`. I'll see if I can do it in the next few days - would you or @dmckinnell be able to kindly resolve this? Not necessarily using the PR #44 I opened that is still unfinished.

**Comment by allanleal** [comment]
@pariterre Just saw you proposed a PR! Thanks.

**Comment by allanleal** [comment]
OK, just merged PR #45 of @pariterre and created a new release v0.5.6 which should soon be available in conda-forge. Please reopen with necessary.
