### ISSUE TITLE
Cannot compile with g++ 6.3.0 or clang 3.8.1

### ISSUE THREAD

**Issue by vmartinlac** [autodiff/autodiff#46]
Hello,

I am looking to use autodiff in my project.
Standard cmake install fails on my device.

`mkdir build; cd build; cmake ../autodiff; make install`

[output.txt](https://github.com/autodiff/autodiff/files/3398377/output.txt)

I have tried using with g++ 6.3.0 or clang 3.8.1
I have tried adding -std=c++17 to CMAKE_CXX_FLAGS but it does not improve (and C++17 is already requested in CMakeLists.txt).

By the way, it would be nice if a cmake option was added to disable building examples.

**Comment by vmartinlac** [comment]
Answer to myself:

"if constexpr" statement requires clang >= 3.9 || gcc >= 7

**Comment by vmartinlac** [comment]
I have tried clang 8 and compilation still fails.
[output.txt](https://github.com/autodiff/autodiff/files/3398479/output.txt)

Which is minimal compiler to use autodiff?

**Comment by allanleal** [comment]
Have you tried using `gcc-7.3.0+`? clang-8 should work - I'm checking here in my machine.

**Comment by allanleal** [comment]
I compiled here using `clang++-8` and everything worked well. Find below the steps I took:

~~~bash
cd autodiff
mkdir build
cd build
export CXX=/usr/bin/clang++-8
export CC=/usr/bin/clang-8
cmake ..
make -j 3
~~~

I have attached a complete log file for the build process. Let me know if the issue persists (by reopening this issue).

[autodiff-build-log-using-clang-8.txt](https://github.com/autodiff/autodiff/files/3407029/autodiff-build-log-using-clang-8.txt)

**Comment by vmartinlac** [comment]
I managed to compile with clang 8.
I had to indicate to use llvm libc++ and libc++abi.
