### ISSUE TITLE
Forward mode: Higher-order derivatives of a multi-variable function

### ISSUE THREAD

**Issue by Georgios-Eric** [autodiff/autodiff#47]
Hi Allan:

Thank you very much for making your library available, and in particular the thought you have invested into making the API so intuittive.

I plan to use your library extensively to compute sensitivities of complicated financial instruments.

At the moment, I am unit testing, with the Catch2 C++ unit test framework, the examples in your tutorial section, and testing the output from autodiff against the answer computed by symbolic differentiation. My development environment is VS2017 (Professional).

Everything looks fine, until I reach the example "Higher-order derivatives of a multi-variable function" in the forward mode. The answer I obtain from autodiff for ux (first derivative of u with respect to x) is 3.192695, but the correct answer should be 2.25; I have not proceeded beyond this point, as I wish to resolve the issue.

Interestingly, I progressively added terms into the definition of the function f, and found that the term log(x/y) seems to be a problem - if I omit this term, then ux is fine.

In the attached zip folder you will find my unit test.

Appreciate any assitance you could provide to resolve my issue. 

[autodiff.zip](https://github.com/autodiff/autodiff/files/3442643/autodiff.zip)

**Comment by allanleal** [comment]
Thanks for reporting this bug - a fix is on the way [here](#48). Let me know if you encounter other issues.

**Comment by allanleal** [comment]
The new release v0.5.7 should now resolve your issue. Thanks for reporting this.
