### ISSUE TITLE
Location of VectorXdual

### ISSUE THREAD

**Issue by ibell** [autodiff/autodiff#61]
In my opinion, the ``VectorXdual`` typedef doesn't belong in the Eigen namespace, I think it would be more sensible to put it in the ``autodiff`` namespace.  It's hard to see this from the examples because the ``using namespace ...`` paradigm is used which obfuscates where things are coming from.

**Comment by allanleal** [comment]
I agree with you. Would you kindly do a pull request with these changes,
and also the ArrayXdual typedefs?

**Comment by ibell** [comment]
Sure!  Happy to do so.  Autodiff is a game changer for me

**Comment by allanleal** [comment]
Great Ian. Your help is much appreciated.

**Comment by allanleal** [comment]
This issue was fixed with PR #63
