### ISSUE TITLE
Example: Gradient of a scalar function with parameters

### ISSUE THREAD

**Issue by ludkinm** [autodiff/autodiff#74]
It was my understanding that the example "Gradient of a scalar function with parameters" should be computing the derivative of f wrt x and wrt p
In maths, I expected ``gx = df/dx = 2*x*exp(sum(p))`` and ``gp=df/dp = p * sum(x*x) * exp(sum(p))``
Which on the example `x=[1,2,3,4,5]` and `p=[1,2,3]` would yield to one decimal place:
```expect_gx = [806.9, 1613.7, 2420.6, 3227.4, 4034.3]```
and
```expect_gp = [22188.6, 44377.2, 66565.8]```

However, when I run the example I get:
```gp = [22188.6, 22188.6, 22188.6]```

Is this because it is a parameter or is my maths bad?

**Comment by ludkinm** [comment]
I'm an idiot. Can you delete this?

**Comment by ludkinm** [comment]
It's bad maths! Don't do calculus after 5pm on Fridays

**Comment by allanleal** [comment]
No worries @ludkinm. Have a nice weekend!
