### ISSUE TITLE
Side effects

### ISSUE THREAD

**Issue by kewp** [autodiff/autodiff#80]
Are there side effects in autodiff? I ask because when I put my solver into a loop I get strange results, even though I use fresh variables each time.

```c++
int n; for (n=1; n<20; n*=2)
{
    Mesh m = get_mesh(n);
    VectorXd U(nn), V(nn);

    solve(mesh,U,V);
}
```

I'm not sure how the variable tracking is done. Is there a way to `reset` autodiff and say "I'm solving a new problem now" ?

**Comment by allanleal** [comment]
Hi Karl, could you please provide a very simple example that reproduces this issue? I see to use of autodiff types in the code snippet you provided originally.

**Comment by kewp** [comment]
Hi Allan.

I'm actually struggling to replicate this with some code. I'm closing this for now. Thanks
