### ISSUE TITLE
Make the Scalar type parameterized in user scope

### ISSUE THREAD

**Issue by Ravenwater** [autodiff/autodiff#93]
In the current design, the type 'dual' is defined inside the autodiff namespace.

If I want to write multi-precision algorithms that uses autodiff, then I need the ability to redefine the dual type on each invocation of autodiff. Something like:

```
template<typename Scalar>
Scalar f(const Scalar& x, const Scalar& y, const Scalar& z) {
    return 1 + x + y + z + x * y + y * z + x * z + x * y*z + exp(x / y + y / z);
}

template<typename Scalar>
void calc_derivatives(const Scalar& x, const Scalar& y, const Scalar& z) {
int main()
{
	Scalar u = f(x, y, z);  // the output scalar u = f(x, y, z)

	Scalar dudx = derivative(f, wrt(x), at(x, y, z));  // evaluate du/dx using ADL to specialize on Scalar type
	Scalar dudy = derivative(f, wrt(y), at(x, y, z));  // evaluate du/dy
	Scalar dudz = derivative(f, wrt(z), at(x, y, z));  // evaluate du/dz

	cout << "u = " << u << endl;         // print the evaluated output u
	cout << "du/dx = " << dudx << endl;  // print the evaluated derivative du/dx
	cout << "du/dy = " << dudy << endl;  // print the evaluated derivative du/dy
	cout << "du/dz = " << dudz << endl;  // print the evaluated derivative du/dz
}

void main() {

     {
        using Scalar = double;
	Scalar x = 1.0;  // the input variable x
	Scalar y = 2.0;  // the input variable y
	Scalar z = 3.0;  // the input variable z
        calc_derivatives(x,y,z);
    }
    {        
        using Scalar = sw::unum::posit<32,2>;
	Scalar x = 1.0;  // the input variable x
	Scalar y = 2.0;  // the input variable y
	Scalar z = 3.0;  // the input variable z
        calc_derivatives(x,y,z);
    }
}
```

**Comment by Ravenwater** [comment]
In general, I would want to take some generic function and give it to derivative:

``` 
namespace some_namespace {

template<typename Scalar>
Scalar f1(const Scalar& x, const Scalar& y, const Scalar& z) {
    return some-expression;
}

template<typename Scalar>
Scalar f2(const Scalar& x, const Scalar& y, const Scalar& z) {
    return some-other-expression;
}
} // some_namespace

...

void main() {
    using namespace some_namespace;

    using p16 = sw::unum::posit<16,1>;
    using p20 = sw::unum::posit<20,1>;
    using p24 = sw::unum::posit<24,1>;

    {
       p16 f1_dudx = derivative(f1, wrt(x), at(1,2,3));
       p20 f2_dudx = derivative(f2, wrt(x), at(1,2,3));
    }
}
```

**Comment by Ravenwater** [comment]
another use case is to calculate errors between precisions

```
    p16 p16_dudx = derivative(f1, wrt(x), at(1,2.3));
    p20 p20_dudx = derivative(f1, wrt(x), at(1,2,3));

    p32 d1 = p16_dudx;
    p32 d2 = p20_dudx;
    p32 diff = d1 - d2;
```

The desire to give at() literals is strong, particular for interpretive C++ environment, such as xeus_cling (https://github.com/QuantStack/xeus-cling)

**Comment by supersega** [comment]
@Ravenwater Not sure that I understand problem. That code which you provided will not work:
E.g. from this case:
```cpp
void main() {
    using namespace some_namespace;

    using p16 = sw::unum::posit<16,1>;
    using p20 = sw::unum::posit<20,1>;
    using p24 = sw::unum::posit<24,1>;

    {
       p16 f1_dudx = derivative(f1, wrt(x), at(1,2,3));
       p20 f2_dudx = derivative(f2, wrt(x), at(1,2,3));
    }
}
```
We **must** pass `autodiff dual` type to `wrt` and `at`.

But I believe you are talking about **implicit cast**. Could you please add more clear description.

**Comment by supersega** [comment]
To get `derivative` works you should pass the same variable to `wrt` and `at`. 
```cpp
p16 f1_dudx = derivative(f1, wrt(x), at(x, 2 , 3));
```

**Comment by Ravenwater** [comment]
@supersega I was making these requests without clearly understanding the autodiff design. It makes sense that you would need to pass the write types to wrt() and at() for all of this machinery to resolve. I need to better understand the forward::Dual type.

Let me experiment with my use case: running derivatives on a function using different precision to measure the error caused by rounding, and I will report back. I'll close this issue for the time being as you have educated me on the user scope use of forward::Dual.

**Comment by Ravenwater** [comment]
All works as expected, this is awesome!

```
// C++ includes
#include <iostream>
using namespace std;

// universal posit number system include
#include <universal/posit/posit>
// autodiff include
#include <autodiff/forward.hpp>
using namespace autodiff;

// Specialize isNumber for complex to make it compatible with dual
namespace autodiff::forward::traits {
	template<std::size_t _nbits, std::size_t _es>
	struct isArithmetic<sw::unum::posit<_nbits, _es>> : std::true_type { };
} // namespace autodiff::forward::traits


// The multi-variable function for which derivatives are needed
template<typename DualType>
DualType f(const DualType x, const DualType y, const DualType z)
{
	return 1 + x + y + z + x * y + y * z + x * z + x * y*z + exp(x / y + y / z);
}

template<typename Scalar>
void CalculateDerivatives() {
	using namespace std;
	using dual = forward::Dual<Scalar, Scalar>;

	dual x = 1.0;  // the input variable x
	dual y = 2.0;  // the input variable y
	dual z = 3.0;  // the input variable z

	dual u = f(x, y, z);  // the output scalar u = f(x, y, z)

	Scalar dudx = derivative(f<dual>, wrt(x), at(x, y, z));  // evaluate du/dx
	Scalar dudy = derivative(f<dual>, wrt(y), at(x, y, z));  // evaluate du/dy
	Scalar dudz = derivative(f<dual>, wrt(z), at(x, y, z));  // evaluate du/dz

	cout << "Scalar type : " << typeid(Scalar).name() << endl;
	cout << "u = " << u << endl;         // print the evaluated output u
	cout << "du/dx = " << dudx << endl;  // print the evaluated derivative du/dx
	cout << "du/dy = " << dudy << endl;  // print the evaluated derivative du/dy
	cout << "du/dz = " << dudz << endl;  // print the evaluated derivative du/dz
}

int main()
{
	CalculateDerivatives< sw::unum::posit<16, 1> >();
	CalculateDerivatives< sw::unum::posit<20, 1> >();
	CalculateDerivatives< sw::unum::posit<24, 1> >();
	CalculateDerivatives< sw::unum::posit<28, 1> >();
	CalculateDerivatives< sw::unum::posit<32, 2> >();
}
```

yields:

```
Scalar type : class sw::unum::posit<16,1>
u = 27.2188
du/dx = 13.6055
du/dy = 8.26563
du/dz = 5.28711
Scalar type : class sw::unum::posit<20,1>
u = 27.2109
du/dx = 13.6055
du/dy = 8.26758
du/dz = 5.28638
Scalar type : class sw::unum::posit<24,1>
u = 27.2113
du/dx = 13.6056
du/dy = 8.26761
du/dz = 5.28638
Scalar type : class sw::unum::posit<28,1>
u = 27.2113
du/dx = 13.6056
du/dy = 8.26761
du/dz = 5.28638
Scalar type : class sw::unum::posit<32,2>
u = 27.2113
du/dx = 13.6056
du/dy = 8.26761
du/dz = 5.28638
```

**Comment by supersega** [comment]
Very nice, this is a result of great @allanleal work.

Btw, am I correctly understand posit design. It has good accuracy around 1? But with very small or big numbers floats are better?

**Comment by Ravenwater** [comment]
@supersega there is a little bit more to it, 😄 but yes, posits are a _tapered_ floating point system that can exchange bits between the exponent and the mantissa. The reason tapering is valuable is that with very large or very small numbers, the information content of the number is in the scale, not the precision, so you would like your number system to leverage that. There has been dozens of tapered number systems proposed through the years, typically some form of log-based mapping, but reinterpretation of the bits, which is how posits do the tapering, is a more 'modern' approach.

A couple more salient attributes of the post number system:
 - symmetric around 1, so there are an equal number of samples between 0 and 1 as there are between 1 and infinity (and same on the negative side)
 - very efficient encoding compared to IEEE floats, there is only one encoding that doesn't represent a number, and that is Not a Real, or NaR. 
 - a new instruction called the fused dot product, which uses a super accumulator to defer rounding (this is the big jump past IEEE as we have user-controlled rounding events. If you don't want to round, you don't have to. This is something that I am looking forward to explore with autodiff, as function evaluation is rife with opportunities for optimization

**Comment by allanleal** [comment]
Great, looks like some good progress was made there. @Ravenwater , I'll try to get in touch with the conda-forge thing in the next week. I have some ideas for using `posit` in my applications. I'm going on vacation today, but I'll try to be active here a bit while away.
