### ISSUE TITLE
higher-order derivatives on a single variable vector function using forward mode

### ISSUE THREAD

**Issue by versatran01** [autodiff/autodiff#95]
I have a question about higher-order derivatives on a vector function using forward mode ad.
This lib has changed a lot since the last time I used it.

Suppose I have this
```c++
struct Functor {
  static constexpr int Dim = 3;
  template <typename T>
  Eigen::Matrix<T, Dim, 1> operator()(const T &x) const {
    Eigen::matrix<T, Dim, 1> Y;
    Y(0) = x;
    Y(1) = x * x;
    Y(2) = x * x * x;
    return Y;
  }
};
```

and I want to compute up to 2nd order derivatives wrt. `x` and put them in a matrix of size 3x3, where each column `c` stores the `c`-th order derivatives.

Is it possible to do something like this?

```c++
template <int Order, typename F>
auto dnY_dxn(F f, real_t x) -> Eigen::Matrix<double, F::Dim, Order + 1> {
  Eigen::Matrix<double, F::Dim, Order + 1> out;
  // what should i do here?
  return out;
}
```
Then I will just call `dnY_dxn<2>(Functor(), 1.0)` to get the result.

I feel like this can't be easily done with the `derivative` function, but could possibly be done with manually calling the function, like what's inside `derivative`?

**Comment by allanleal** [comment]
Sorry for the delay, I'm on vacation. Could you please simplify the example, and post something minimal that works? 

Check if this [tutorial](https://autodiff.github.io/tutorials/#higher-order-derivatives-of-a-multi-variable-function) helps. You'll need to use `using dual2nd = HigherOrderDual<2>;` to allow 2nd order derivatives.
